const API='https://api.binance.com/api/v3';
const WATCH=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','ADAUSDT','TRXUSDT','LINKUSDT','AVAXUSDT','DOTUSDT'];
const names={BTCUSDT:'Bitcoin',ETHUSDT:'Ethereum',BNBUSDT:'BNB',SOLUSDT:'Solana',XRPUSDT:'XRP',ADAUSDT:'Cardano',TRXUSDT:'TRON',LINKUSDT:'Chainlink',AVAXUSDT:'Avalanche',DOTUSDT:'Polkadot'};
const state={symbol:'BTCUSDT',interval:'15m',ticker:[],klines:[],loading:false};
const $=id=>document.getElementById(id);
const fmt=(n,d=2)=>Number(n).toLocaleString('en-US',{maximumFractionDigits:d});
const api=async(path)=>{const r=await fetch(API+path,{cache:'no-store'});if(!r.ok)throw Error('تعذر الوصول إلى Binance (HTTP '+r.status+')');return r.json()};
function symbolName(s){return names[s]||s.replace('USDT','')}
function logo(s){return s==='BTCUSDT'?'₿':s.replace('USDT','').slice(0,2)}
function showError(message){const box=$('errorBox');box.textContent='⚠️ '+message;box.hidden=false}
function clearError(){$('errorBox').hidden=true;$('errorBox').textContent=''}
async function loadTickers(){state.ticker=await api('/ticker/24hr?symbols='+encodeURIComponent(JSON.stringify(WATCH)));renderTickers();renderCoins();selectCurrent()}
function renderTickers(){const map=Object.fromEntries(state.ticker.map(x=>[x.symbol,x]));$('tickerGrid').innerHTML=WATCH.slice(0,4).map(s=>{const x=map[s];if(!x)return '';const c=+x.priceChangePercent;return `<div class="ticker"><span>${symbolName(s)} · ${s.replace('USDT','/USDT')}</span><b>$${fmt(x.lastPrice,2)}</b><span class="${c>=0?'up':'down'}">${c>=0?'+':''}${fmt(c,2)}%</span></div>`}).join('')}
let activeFilter='all';
function renderCoins(){const q=$('searchInput').value.trim().toUpperCase();let arr=state.ticker.filter(x=>{const symbol=x.symbol, name=symbolName(symbol).toUpperCase();return WATCH.includes(symbol)&&(!q||name.includes(q)||symbol.includes(q))});if(activeFilter==='positive')arr=arr.filter(x=>+x.priceChangePercent>=0);if(activeFilter==='negative')arr=arr.filter(x=>+x.priceChangePercent<0);$('coinCount').textContent=arr.length;$('coinList').innerHTML=arr.length?arr.map(x=>{const c=+x.priceChangePercent;return `<div class="coin ${x.symbol===state.symbol?'selected':''}" data-symbol="${x.symbol}" tabindex="0" role="button"><div class="coin-left"><div class="mini-logo">${logo(x.symbol)}</div><div><strong>${x.symbol.replace('USDT','/USDT')}</strong><small>${symbolName(x.symbol)}</small></div></div><div class="coin-price">$${fmt(x.lastPrice,2)}<small class="${c>=0?'up':'down'}">${c>=0?'+':''}${fmt(c,2)}%</small></div></div>`}).join(''):'<p class="mini-note">لا توجد نتائج مطابقة.</p>';document.querySelectorAll('.coin').forEach(e=>{const choose=()=>{state.symbol=e.dataset.symbol;loadAnalysis()};e.onclick=choose;e.onkeydown=ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();choose()}}})}
function selectCurrent(){document.querySelectorAll('.coin').forEach(e=>e.classList.toggle('selected',e.dataset.symbol===state.symbol))}
async function loadAnalysis(){if(state.loading)return;state.loading=true;clearError();try{$('engineState').textContent='جارٍ التحليل…';selectCurrent();const [ticker,klines]=await Promise.all([api('/ticker/24hr?symbol='+state.symbol),api(`/klines?symbol=${state.symbol}&interval=${state.interval}&limit=180`)]);if(!Array.isArray(klines)||klines.length<60)throw Error('بيانات الشموع غير كافية للتحليل');state.klines=klines;renderAsset(ticker);drawChart();const a=analyze(klines);renderAnalysis(a);$('engineState').textContent='التحليل مكتمل';$('updatedAt').textContent='آخر تحديث '+new Date().toLocaleTimeString('ar-YE',{hour:'2-digit',minute:'2-digit'});}catch(e){$('engineState').textContent='تعذر جلب البيانات';showError(e.message+' — تحقق من الإنترنت أو جرّب التحديث لاحقًا.')}finally{state.loading=false}}
function renderAsset(t){const c=+t.priceChangePercent;$('assetLogo').textContent=logo(state.symbol);$('assetSymbol').textContent=state.symbol.replace('USDT','/USDT');$('assetName').textContent=symbolName(state.symbol);$('assetPrice').textContent='$'+fmt(t.lastPrice,2);$('assetChange').textContent=(c>=0?'+':'')+fmt(c,2)+'%';$('assetChange').className=c>=0?'up':'down'}
function ema(values,p){const k=2/(p+1);let e=values.slice(0,p).reduce((a,b)=>a+b,0)/p;const out=Array(p-1).fill(null);out.push(e);for(let i=p;i<values.length;i++){e=values[i]*k+e*(1-k);out.push(e)}return out}
function rsi(v,p=14){const out=Array(v.length).fill(null);let gains=0,losses=0;for(let i=1;i<=p;i++){const d=v[i]-v[i-1];if(d>=0)gains+=d;else losses-=d}let ag=gains/p,al=losses/p;out[p]=al===0?100:100-100/(1+ag/al);for(let i=p+1;i<v.length;i++){const d=v[i]-v[i-1];ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p;out[i]=al===0?100:100-100/(1+ag/al)}return out}
function atr(k,p=14){const tr=k.map((x,i)=>i?Math.max(+x[2]-+x[3],Math.abs(+x[2]-+k[i-1][4]),Math.abs(+x[3]-+k[i-1][4])):+x[2]-+x[3]);let a=tr.slice(0,p).reduce((x,y)=>x+y,0)/p;const out=Array(p-1).fill(null);out.push(a);for(let i=p;i<tr.length;i++){a=(a*(p-1)+tr[i])/p;out.push(a)}return out}
function analyze(k){const close=k.map(x=>+x[4]),vol=k.map(x=>+x[5]),e20=ema(close,20),e50=ema(close,50),r=rsi(close),a=atr(k);const i=close.length-1,p=close[i],rv=r[i],atrv=a[i],volAvg=vol.slice(-20).reduce((x,y)=>x+y,0)/20;let score=0,reasons=[];if(p>e20[i]){score+=20;reasons.push('السعر فوق EMA20')}else{score-=20;reasons.push('السعر تحت EMA20')}if(e20[i]>e50[i]){score+=20;reasons.push('الاتجاه المتوسط صاعد')}else{score-=20;reasons.push('الاتجاه المتوسط هابط')}if(rv>55&&rv<72){score+=20;reasons.push('الزخم إيجابي')}else if(rv<45){score-=20;reasons.push('الزخم ضعيف')}else{reasons.push('RSI محايد')}if(vol[i]>volAvg*1.15){score+=(p>=close[i-1]?15:-15);reasons.push('حجم تداول مرتفع')}else{reasons.push('الحجم طبيعي')}const momentum=(p-close[i-4])/close[i-4]*100;if(momentum>0){score+=15;reasons.push('زخم قصير المدى إيجابي')}else{score-=15;reasons.push('زخم قصير المدى سلبي')}score=Math.max(-100,Math.min(100,score));let signal=score>=55?'شراء':score<=-55?'بيع':'انتظار';let confidence=Math.round(50+Math.abs(score)*.45);if(signal==='انتظار')confidence=Math.max(50,confidence-8);return{score,signal,confidence,p,rv,atr:atrv,reasons,e20:e20[i],e50:e50[i]}}
function renderAnalysis(a){const card=$('signalCard');card.classList.remove('buy','sell','wait');card.classList.add(a.signal==='شراء'?'buy':a.signal==='بيع'?'sell':'wait');$('signalText').textContent=a.signal;$('signalReason').textContent=a.reasons.slice(0,3).join(' · ');$('confidence').textContent=a.confidence+'%';const p=a.p,sl=a.signal==='شراء'?p-a.atr*1.4:p+a.atr*1.4,t1=a.signal==='شراء'?p+a.atr*2:p-a.atr*2,t2=a.signal==='شراء'?p+a.atr*3.2:p-a.atr*3.2;$('entry').textContent='$'+fmt(p,2);$('stop').textContent='$'+fmt(sl,2);$('target1').textContent='$'+fmt(t1,2);$('target2').textContent='$'+fmt(t2,2);$('metrics').innerHTML=[['RSI',fmt(a.rv,1)],['EMA 20','$'+fmt(a.e20,2)],['EMA 50','$'+fmt(a.e50,2)],['ATR','$'+fmt(a.atr,2)]].map(x=>`<div class="metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
function drawChart(){const c=$('chart'),ctx=c.getContext('2d'),dpr=window.devicePixelRatio||1,w=c.clientWidth,h=270;c.width=Math.max(1,w*dpr);c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const data=state.klines.map(x=>+x[4]);if(data.length<2)return;const min=Math.min(...data),max=Math.max(...data),pad=18;ctx.strokeStyle='#17243b';ctx.lineWidth=1;for(let j=1;j<5;j++){const y=pad+j*(h-pad*2)/5;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.beginPath();data.forEach((v,i)=>{const x=i*(w-8)/(data.length-1)+4,y=h-pad-(v-min)/(max-min||1)*(h-pad*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#8fa9ff';ctx.lineWidth=2.2;ctx.stroke();ctx.lineTo(w-4,h);ctx.lineTo(4,h);ctx.closePath();ctx.globalAlpha=.08;ctx.fillStyle='#8fa9ff';ctx.fill();ctx.globalAlpha=1}
async function refresh(){if(state.loading)return;try{$('refreshBtn').disabled=true;$('refreshBtn').textContent='…';$('engineState').textContent='تحديث البيانات…';await loadTickers();await loadAnalysis()}catch(e){showError(e.message+' — تحقق من اتصال الإنترنت.');$('engineState').textContent='تعذر الاتصال'}finally{$('refreshBtn').disabled=false;$('refreshBtn').textContent='↻'}}
document.querySelectorAll('.tf').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tf').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.interval=b.dataset.interval;loadAnalysis()});document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderCoins()});$('searchInput').oninput=renderCoins;$('refreshBtn').onclick=refresh;window.addEventListener('resize',()=>state.klines.length&&drawChart());refresh();
