const API='https://api.binance.com/api/v3';
const WATCH=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','ADAUSDT','TRXUSDT','LINKUSDT','AVAXUSDT','DOTUSDT'];
const names={BTCUSDT:'Bitcoin',ETHUSDT:'Ethereum',BNBUSDT:'BNB',SOLUSDT:'Solana',XRPUSDT:'XRP',ADAUSDT:'Cardano',TRXUSDT:'TRON',LINKUSDT:'Chainlink',AVAXUSDT:'Avalanche',DOTUSDT:'Polkadot'};
const state={symbol:'BTCUSDT',interval:'15m',ticker:[],klines:[],loading:false,lastSignal:null,lastPrice:null,alertEnabled:false};
const $=id=>document.getElementById(id); const fmt=(n,d=2)=>Number(n).toLocaleString('en-US',{maximumFractionDigits:d});
const api=async path=>{const r=await fetch(API+path,{cache:'no-store'});if(!r.ok)throw Error('تعذر الوصول إلى Binance (HTTP '+r.status+')');return r.json()};
function symbolName(s){return names[s]||s.replace('USDT','')} function logo(s){return s==='BTCUSDT'?'₿':s.replace('USDT','').slice(0,2)}
function showError(m){const b=$('errorBox');b.textContent='⚠️ '+m;b.hidden=false} function clearError(){$('errorBox').hidden=true;$('errorBox').textContent=''}
async function loadTickers(){state.ticker=await api('/ticker/24hr?symbols='+encodeURIComponent(JSON.stringify(WATCH)));renderTickers();renderCoins();selectCurrent()}
function renderTickers(){const map=Object.fromEntries(state.ticker.map(x=>[x.symbol,x]));$('tickerGrid').innerHTML=WATCH.slice(0,4).map(s=>{const x=map[s];if(!x)return '';const c=+x.priceChangePercent;return `<div class="ticker"><span>${symbolName(s)} · ${s.replace('USDT','/USDT')}</span><b>$${fmt(x.lastPrice,2)}</b><span class="${c>=0?'up':'down'}">${c>=0?'+':''}${fmt(c,2)}%</span></div>`}).join('')}
let activeFilter='all';
function renderCoins(){const q=$('searchInput').value.trim().toUpperCase();let arr=state.ticker.filter(x=>{const s=x.symbol,n=symbolName(s).toUpperCase();return WATCH.includes(s)&&(!q||n.includes(q)||s.includes(q))});if(activeFilter==='positive')arr=arr.filter(x=>+x.priceChangePercent>=0);if(activeFilter==='negative')arr=arr.filter(x=>+x.priceChangePercent<0);$('coinCount').textContent=arr.length;$('coinList').innerHTML=arr.length?arr.map(x=>{const c=+x.priceChangePercent;return `<div class="coin ${x.symbol===state.symbol?'selected':''}" data-symbol="${x.symbol}" tabindex="0" role="button"><div class="coin-left"><div class="mini-logo">${logo(x.symbol)}</div><div><strong>${x.symbol.replace('USDT','/USDT')}</strong><small>${symbolName(x.symbol)}</small></div></div><div class="coin-price">$${fmt(x.lastPrice,2)}<small class="${c>=0?'up':'down'}">${c>=0?'+':''}${fmt(c,2)}%</small></div></div>`}).join(''):'<p class="mini-note">لا توجد نتائج مطابقة.</p>';document.querySelectorAll('.coin').forEach(e=>{const choose=()=>{state.symbol=e.dataset.symbol;loadAnalysis()};e.onclick=choose;e.onkeydown=ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();choose()}}})}
function selectCurrent(){document.querySelectorAll('.coin').forEach(e=>e.classList.toggle('selected',e.dataset.symbol===state.symbol))}
async function loadAnalysis(){if(state.loading)return;state.loading=true;clearError();try{$('engineState').textContent='جارٍ تحليل الشموع الحقيقية…';selectCurrent();const [ticker,klines]=await Promise.all([api('/ticker/24hr?symbol='+state.symbol),api(`/klines?symbol=${state.symbol}&interval=${state.interval}&limit=180`)]);if(!Array.isArray(klines)||klines.length<60)throw Error('بيانات الشموع غير كافية');state.klines=klines.slice(0,-1);renderAsset(ticker);drawChart();const a=analyze(state.klines);renderAnalysis(a);handleSignalAlert(a,+ticker.lastPrice);$('engineState').textContent='التحليل مكتمل · LIVE';$('updatedAt').textContent='آخر تحديث '+new Date().toLocaleTimeString('ar-YE',{hour:'2-digit',minute:'2-digit'});}catch(e){$('engineState').textContent='تعذر جلب البيانات';showError(e.message+' — تحقق من الإنترنت.')}finally{state.loading=false}}
function renderAsset(t){const c=+t.priceChangePercent;$('assetLogo').textContent=logo(state.symbol);$('assetSymbol').textContent=state.symbol.replace('USDT','/USDT');$('assetName').textContent=symbolName(state.symbol);$('assetPrice').textContent='$'+fmt(t.lastPrice,2);$('assetChange').textContent=(c>=0?'+':'')+fmt(c,2)+'%';$('assetChange').className=c>=0?'up':'down';state.lastPrice=+t.lastPrice}
function ema(v,p){const k=2/(p+1);let e=v.slice(0,p).reduce((a,b)=>a+b,0)/p,out=Array(p-1).fill(null);out.push(e);for(let i=p;i<v.length;i++){e=v[i]*k+e*(1-k);out.push(e)}return out}
function rsi(v,p=14){const o=Array(v.length).fill(null);let g=0,l=0;for(let i=1;i<=p;i++){const d=v[i]-v[i-1];if(d>=0)g+=d;else l-=d}let ag=g/p,al=l/p;o[p]=al===0?100:100-100/(1+ag/al);for(let i=p+1;i<v.length;i++){const d=v[i]-v[i-1];ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p;o[i]=al===0?100:100-100/(1+ag/al)}return o}
function atr(k,p=14){const tr=k.map((x,i)=>i?Math.max(+x[2]-+x[3],Math.abs(+x[2]-+k[i-1][4]),Math.abs(+x[3]-+k[i-1][4])):+x[2]-+x[3]);let a=tr.slice(0,p).reduce((x,y)=>x+y,0)/p,o=Array(p-1).fill(null);o.push(a);for(let i=p;i<tr.length;i++){a=(a*(p-1)+tr[i])/p;o.push(a)}return o}
function analyze(k){const close=k.map(x=>+x[4]),vol=k.map(x=>+x[5]),e20=ema(close,20),e50=ema(close,50),r=rsi(close),a=atr(k),i=close.length-1,p=close[i],rv=r[i],av=a[i],va=vol.slice(-20).reduce((x,y)=>x+y,0)/20;let score=0,re=[];if(p>e20[i]){score+=20;re.push('السعر فوق EMA20')}else{score-=20;re.push('السعر تحت EMA20')}if(e20[i]>e50[i]){score+=20;re.push('الاتجاه المتوسط صاعد')}else{score-=20;re.push('الاتجاه المتوسط هابط')}if(rv>55&&rv<72){score+=20;re.push('RSI يدعم الزخم')}else if(rv<45){score-=20;re.push('RSI ضعيف')}else re.push('RSI محايد');if(vol[i]>va*1.15){score+=(p>=close[i-1]?15:-15);re.push('حجم التداول مرتفع')}else re.push('الحجم طبيعي');const mom=(p-close[i-4])/close[i-4]*100;if(mom>0){score+=15;re.push('الزخم القصير إيجابي')}else{score-=15;re.push('الزخم القصير سلبي')}score=Math.max(-100,Math.min(100,score));const signal=score>=55?'شراء':score<=-55?'بيع':'انتظار';let confidence=Math.round(50+Math.abs(score)*.45);if(signal==='انتظار')confidence=Math.max(50,confidence-8);return{score,signal,confidence,p,rv,atr:av,reasons:re,e20:e20[i],e50:e50[i]}}
function renderAnalysis(a){const card=$('signalCard');card.classList.remove('buy','sell','wait');card.classList.add(a.signal==='شراء'?'buy':a.signal==='بيع'?'sell':'wait');$('signalIcon').textContent=a.signal==='شراء'?'↗':a.signal==='بيع'?'↘':'◎';$('signalText').textContent=a.signal;$('signalReason').textContent=a.reasons.slice(0,4).join(' · ');$('confidence').textContent=a.confidence+'%';const p=a.p,sl=a.signal==='شراء'?p-a.atr*1.4:p+a.atr*1.4,t1=a.signal==='شراء'?p+a.atr*2:p-a.atr*2,t2=a.signal==='شراء'?p+a.atr*3.2:p-a.atr*3.2;$('entry').textContent='$'+fmt(p,2);$('stop').textContent='$'+fmt(sl,2);$('target1').textContent='$'+fmt(t1,2);$('target2').textContent='$'+fmt(t2,2);$('metrics').innerHTML=[['RSI',fmt(a.rv,1)],['EMA 20','$'+fmt(a.e20,2)],['EMA 50','$'+fmt(a.e50,2)],['ATR','$'+fmt(a.atr,2)]].map(x=>`<div class="metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
function drawChart(){const c=$('chart'),ctx=c.getContext('2d'),dpr=window.devicePixelRatio||1,w=c.clientWidth,h=300;c.width=Math.max(1,w*dpr);c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const k=state.klines.slice(-100);if(k.length<2)return;const highs=k.map(x=>+x[2]),lows=k.map(x=>+x[3]),max=Math.max(...highs),min=Math.min(...lows),pad={t:14,b:28,l:8,r:58},cw=(w-pad.l-pad.r)/k.length,range=max-min||1;ctx.font='9px Cairo';ctx.strokeStyle='#1c201d';ctx.lineWidth=1;for(let j=0;j<5;j++){const y=pad.t+j*(h-pad.t-pad.b)/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();const val=max-j*range/4;ctx.fillStyle='#666c75';ctx.fillText('$'+fmt(val,2),w-pad.r+5,y+3)}const vh=Math.max(...k.map(x=>+x[5]));k.forEach((x,i)=>{const o=+x[1],hi=+x[2],lo=+x[3],cl=+x[4],cx=pad.l+i*cw+cw/2,y=v=>pad.t+(max-v)/range*(h-pad.t-pad.b-40),body=Math.max(2,Math.abs(y(o)-y(cl))),up=cl>=o;ctx.strokeStyle=up?'#43dfa0':'#ff637d';ctx.fillStyle=up?'#43dfa0':'#ff637d';ctx.beginPath();ctx.moveTo(cx,y(hi));ctx.lineTo(cx,y(lo));ctx.stroke();ctx.fillRect(cx-cw*.31,Math.min(y(o),y(cl)),Math.max(2,cw*.62),body);const barH=(+x[5]/vh)*28;ctx.globalAlpha=.22;ctx.fillRect(cx-cw*.31,h-pad.b-barH,Math.max(2,cw*.62),barH);ctx.globalAlpha=1});ctx.fillStyle='#777d87';ctx.fillText('100 شمعة مغلقة',8,h-8)}
function notifyUser(title,body){try{if('Notification' in window&&Notification.permission==='granted')new Notification(title,{body});}catch(e){}if(navigator.vibrate)navigator.vibrate([180,80,180])}
function handleSignalAlert(a,current){if(!state.alertEnabled)return;if(state.lastSignal&&a.signal!==state.lastSignal&&a.signal!=='انتظار'){const word=a.signal==='شراء'?'شراء الآن':'بيع الآن';notifyUser(`GOLDAN AI · ${word}`,`${state.symbol.replace('USDT','/USDT')} — السعر الحالي $${fmt(current,2)} — الإشارة تغيّرت إلى ${a.signal}.`);$('alertTitle').textContent=`${word} · ${state.symbol.replace('USDT','/USDT')}`;$('alertText').textContent=`السعر الحالي $${fmt(current,2)} · إشارة جديدة من تحليل السوق.`}state.lastSignal=a.signal}
async function enableAlerts(){state.alertEnabled=true;$('alertBtn').textContent='مفعّلة';$('alertBtn').disabled=true;$('alertText').textContent='التنبيه المحلي مفعّل. يعمل بقوة أكبر مع بقاء GOLDAN AI في الخلفية.';try{if('Notification' in window){const p=await Notification.requestPermission();if(p!=='granted')$('alertText').textContent='لم تسمح بالإشعارات. يمكنك تفعيلها من إعدادات Android.'}}catch(e){}};
function refresh(){if(state.loading)return;$('refreshBtn').disabled=true;$('refreshBtn').textContent='…';Promise.all([loadTickers(),loadAnalysis()]).catch(e=>showError(e.message)).finally(()=>{$('refreshBtn').disabled=false;$('refreshBtn').textContent='↻'})}
document.querySelectorAll('.tf').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tf').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.interval=b.dataset.interval;loadAnalysis()});document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderCoins()});$('searchInput').oninput=renderCoins;$('refreshBtn').onclick=refresh;$('alertBtn').onclick=enableAlerts;window.addEventListener('resize',()=>state.klines.length&&drawChart());setInterval(()=>{if(!state.loading)loadAnalysis()},30000);refresh();
