const API='https://api.binance.com/api/v3';
const WATCH=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','ADAUSDT','TRXUSDT','LINKUSDT','AVAXUSDT','DOTUSDT'];
const names={BTCUSDT:'Bitcoin',ETHUSDT:'Ethereum',BNBUSDT:'BNB',SOLUSDT:'Solana',XRPUSDT:'XRP',ADAUSDT:'Cardano',TRXUSDT:'TRON',LINKUSDT:'Chainlink',AVAXUSDT:'Avalanche',DOTUSDT:'Polkadot'};
const state={symbol:'BTCUSDT',interval:'15m',ticker:[],klines:[],loading:false,lastSignal:null,lastPrice:null,alertEnabled:false,socket:null,liveKline:null,socketGeneration:0,lastAlertKey:null,pendingSignal:null,pendingCount:0};
const $=id=>document.getElementById(id); const fmt=(n,d=2)=>Number(n).toLocaleString('en-US',{maximumFractionDigits:d});
const api=async path=>{const r=await fetch(API+path,{cache:'no-store'});if(!r.ok)throw Error('تعذر الوصول إلى Binance (HTTP '+r.status+')');return r.json()};
function symbolName(s){return names[s]||s.replace('USDT','')} function logo(s){return s==='BTCUSDT'?'₿':s.replace('USDT','').slice(0,2)}
function showError(m){const b=$('errorBox');if(b){b.textContent='⚠️ '+m;b.hidden=false}} function clearError(){const b=$('errorBox');if(b){b.hidden=true;b.textContent=''}}
async function loadTickers(){state.ticker=await api('/ticker/24hr?symbols='+encodeURIComponent(JSON.stringify(WATCH)));renderTickers();renderCoins();selectCurrent()}
function renderTickers(){const map=Object.fromEntries(state.ticker.map(x=>[x.symbol,x]));$('tickerGrid').innerHTML=WATCH.slice(0,4).map(s=>{const x=map[s];if(!x)return '';const c=+x.priceChangePercent;return `<div class="ticker"><span>${symbolName(s)} · ${s.replace('USDT','/USDT')}</span><b>$${fmt(x.lastPrice,2)}</b><span class="${c>=0?'up':'down'}">${c>=0?'+':''}${fmt(c,2)}%</span></div>`}).join('')}
let activeFilter='all';
function renderCoins(){const q=$('searchInput').value.trim().toUpperCase();let arr=state.ticker.filter(x=>{const s=x.symbol,n=symbolName(s).toUpperCase();return WATCH.includes(s)&&(!q||n.includes(q)||s.includes(q))});if(activeFilter==='positive')arr=arr.filter(x=>+x.priceChangePercent>=0);if(activeFilter==='negative')arr=arr.filter(x=>+x.priceChangePercent<0);$('coinCount').textContent=arr.length;$('coinList').innerHTML=arr.length?arr.map(x=>{const c=+x.priceChangePercent;return `<div class="coin ${x.symbol===state.symbol?'selected':''}" data-symbol="${x.symbol}" tabindex="0" role="button"><div class="coin-left"><div class="mini-logo">${logo(x.symbol)}</div><div><strong>${x.symbol.replace('USDT','/USDT')}</strong><small>${symbolName(x.symbol)}</small></div></div><div class="coin-price">$${fmt(x.lastPrice,2)}<small class="${c>=0?'up':'down'}">${c>=0?'+':''}${fmt(c,2)}%</small></div></div>`}).join(''):'<p class="mini-note">لا توجد نتائج مطابقة.</p>';document.querySelectorAll('.coin').forEach(e=>{const choose=()=>{state.symbol=e.dataset.symbol;stopLiveStream();state.lastSignal=null;state.pendingSignal=null;state.pendingCount=0;loadAnalysis()};e.onclick=choose;e.onkeydown=ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();choose()}}})}
function selectCurrent(){document.querySelectorAll('.coin').forEach(e=>e.classList.toggle('selected',e.dataset.symbol===state.symbol))}
async function loadAnalysis(){if(state.loading)return;state.loading=true;clearError();try{$('engineState').textContent='جارٍ تحليل الشموع الحقيقية…';selectCurrent();const [ticker,klines]=await Promise.all([api('/ticker/24hr?symbol='+state.symbol),api(`/klines?symbol=${state.symbol}&interval=${state.interval}&limit=500`)]);if(!Array.isArray(klines)||klines.length<80)throw Error('بيانات الشموع غير كافية');state.klines=klines.slice(0,-1);state.liveKline=null;renderAsset(ticker);const a=analyze(state.klines);renderAnalysis(a);drawChart();handleSignalAlert(a,+ticker.lastPrice,true);connectLiveStream();$('engineState').textContent='LIVE · Binance WebSocket';$('updatedAt').textContent='آخر تحديث '+new Date().toLocaleTimeString('ar-YE',{hour:'2-digit',minute:'2-digit'});}catch(e){$('engineState').textContent='تعذر جلب البيانات';showError(e.message+' — تحقق من الإنترنت.')}finally{state.loading=false}}
function stopLiveStream(){state.socketGeneration++;if(state.socket){try{state.socket.close()}catch(e){}}state.socket=null;state.liveKline=null}
function connectLiveStream(){stopLiveStream();const gen=state.socketGeneration;const url=`wss://stream.binance.com:9443/ws/${state.symbol.toLowerCase()}@kline_${state.interval}`;try{const ws=new WebSocket(url);state.socket=ws;ws.onopen=()=>{if(gen===state.socketGeneration)$('engineState').textContent='LIVE · Binance WebSocket'};ws.onmessage=ev=>{if(gen!==state.socketGeneration)return;try{const d=JSON.parse(ev.data),x=d.k;if(!x)return;const k=[+x.t,+x.o,+x.h,+x.l,+x.c,+x.v,+x.T];state.liveKline=k;state.lastPrice=+x.c;$('assetPrice').textContent='$'+fmt(+x.c,2);$('updatedAt').textContent='مباشر '+new Date().toLocaleTimeString('ar-YE',{hour:'2-digit',minute:'2-digit'});const live=[...state.klines,k];const a=analyze(live);renderAnalysis(a);drawChart();handleSignalAlert(a,+x.c,false);if(x.x){state.klines=[...state.klines,k];state.liveKline=null;state.lastSignal=a.signal;loadAnalysis()}}catch(e){}};ws.onerror=()=>{if(gen===state.socketGeneration)$('engineState').textContent='LIVE عبر Binance · إعادة الاتصال…'};ws.onclose=()=>{if(gen===state.socketGeneration){state.socket=null;setTimeout(()=>{if(gen===state.socketGeneration)connectLiveStream()},5000)}}}catch(e){if(gen===state.socketGeneration)$('engineState').textContent='LIVE عبر REST · WebSocket غير متاح'}}
function renderAsset(t){const c=+t.priceChangePercent;const sym=$('assetSymbol'),nm=$('assetName'),pr=$('assetPrice'),ch=$('assetChange');if(sym)sym.textContent=state.symbol.replace('USDT','/USDT');if(nm)nm.textContent=symbolName(state.symbol);if(pr)pr.textContent='$'+fmt(t.lastPrice,2);if(ch){ch.textContent=(c>=0?'+':'')+fmt(c,2)+'%';ch.className=c>=0?'up':'down'}state.lastPrice=+t.lastPrice}
function ema(v,p){if(v.length<p)return Array(v.length).fill(null);const k=2/(p+1);let e=v.slice(0,p).reduce((a,b)=>a+b,0)/p,out=Array(p-1).fill(null);out.push(e);for(let i=p;i<v.length;i++){e=v[i]*k+e*(1-k);out.push(e)}return out}
function rsi(v,p=14){const o=Array(v.length).fill(null);if(v.length<=p)return o;let g=0,l=0;for(let i=1;i<=p;i++){const d=v[i]-v[i-1];if(d>=0)g+=d;else l-=d}let ag=g/p,al=l/p;o[p]=al===0?100:100-100/(1+ag/al);for(let i=p+1;i<v.length;i++){const d=v[i]-v[i-1];ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p;o[i]=al===0?100:100-100/(1+ag/al)}return o}
function atr(k,p=14){const tr=k.map((x,i)=>i?Math.max(+x[2]-+x[3],Math.abs(+x[2]-+k[i-1][4]),Math.abs(+x[3]-+k[i-1][4])):+x[2]-+x[3]);if(tr.length<p)return Array(k.length).fill(null);let a=tr.slice(0,p).reduce((x,y)=>x+y,0)/p,o=Array(p-1).fill(null);o.push(a);for(let i=p;i<tr.length;i++){a=(a*(p-1)+tr[i])/p;o.push(a)}return o}
function macd(v){const e12=ema(v,12),e26=ema(v,26),m=v.map((_,i)=>e12[i]!=null&&e26[i]!=null?e12[i]-e26[i]:null);const valid=m.map(x=>x==null?0:x);const sig=ema(valid,9);return{m,sig}}
function boll(v,p=20,mult=2){const mid=Array(v.length).fill(null),up=Array(v.length).fill(null),lo=Array(v.length).fill(null);for(let i=p-1;i<v.length;i++){const a=v.slice(i-p+1,i+1),mean=a.reduce((x,y)=>x+y,0)/p,sd=Math.sqrt(a.reduce((x,y)=>x=>x+(y-mean)*(y-mean),0)/p);mid[i]=mean;up[i]=mean+mult*sd;lo[i]=mean-mult*sd}return{mid,up,lo}}
function analyze(k){const close=k.map(x=>+x[4]),vol=k.map(x=>+x[5]),e20=ema(close,20),e50=ema(close,50),r=rsi(close),a=atr(k),mc=macd(close),bb=boll(close),i=close.length-1,p=close[i],prev=close[i-1],rv=r[i],av=a[i]||p*.003,va=vol.slice(-20).reduce((x,y)=>x+y,0)/20;let score=0,re=[];
if(p>e20[i]){score+=18;re.push('السعر فوق EMA20')}else{score-=18;re.push('السعر تحت EMA20')}
if(e20[i]>e50[i]&&e20[i]>e20[i-1]){score+=18;re.push('الاتجاه EMA20/50 صاعد')}else if(e20[i]<e50[i]&&e20[i]<e20[i-1]){score-=18;re.push('الاتجاه EMA20/50 هابط')}else re.push('اتجاه متوسط مختلط');
if(rv>=52&&rv<=68){score+=14;re.push('RSI إيجابي ومتوازن')}else if(rv>=32&&rv<48){score-=14;re.push('RSI سلبي ومتوازن')}else if(rv>75){score-=8;re.push('RSI مرتفع جداً')}else if(rv<25){score+=8;re.push('RSI منخفض جداً')}else re.push('RSI محايد');
if(mc.m[i]!=null&&mc.sig[i]!=null){if(mc.m[i]>mc.sig[i]&&mc.m[i]>0){score+=15;re.push('MACD صاعد')}else if(mc.m[i]<mc.sig[i]&&mc.m[i]<0){score-=15;re.push('MACD هابط')}else re.push('MACD محايد')}
if(bb.up[i]&&p>bb.mid[i])score+=8;else if(bb.lo[i]&&p<bb.mid[i])score-=8;
if(vol[i]>va*1.15){score+=(p>=prev?12:-12);re.push('حجم التداول مرتفع')}else re.push('الحجم طبيعي');
const mom=(p-close[Math.max(0,i-4)])/close[Math.max(0,i-4)]*100;if(mom>0.15){score+=10;re.push('الزخم القصير إيجابي')}else if(mom<-0.15){score-=10;re.push('الزخم القصير سلبي')}else re.push('الزخم القصير ضعيف');
score=Math.max(-100,Math.min(100,Math.round(score)));const signal=score>=58?'شراء':score<=-58?'بيع':'انتظار';const confidence=signal==='انتظار'?Math.max(45,Math.round(50+Math.abs(score)*.25)):Math.min(95,Math.round(55+Math.abs(score)*.4));return{score,signal,confidence,p,rv,atr:av,reasons:re,e20:e20[i],e50:e50[i],macd:mc.m[i],macdSignal:mc.sig[i],boll:bb.mid[i]}}
function renderAnalysis(a){const card=$('signalCard');if(card){card.classList.remove('buy','sell','wait');card.classList.add(a.signal==='شراء'?'buy':a.signal==='بيع'?'sell':'wait')}const si=$('signalIcon'),st=$('signalText'),sr=$('signalReason'),cf=$('confidence');if(si)si.textContent=a.signal==='شراء'?'↗':a.signal==='بيع'?'↘':'◎';if(st)st.textContent=a.signal;if(sr)sr.textContent=a.reasons.slice(0,5).join(' · ');if(cf)cf.textContent=a.confidence+'%';const p=a.p,sl=a.signal==='شراء'?p-a.atr*1.4:p+a.atr*1.4,t1=a.signal==='شراء'?p+a.atr*2:p-a.atr*2,t2=a.signal==='شراء'?p+a.atr*3.2:p-a.atr*3.2;if($('entry'))$('entry').textContent='$'+fmt(p,2);if($('stop'))$('stop').textContent='$'+fmt(sl,2);if($('target1'))$('target1').textContent='$'+fmt(t1,2);if($('target2'))$('target2').textContent='$'+fmt(t2,2);if($('metrics'))$('metrics').innerHTML=[['RSI',fmt(a.rv,1)],['EMA 20','$'+fmt(a.e20,2)],['EMA 50','$'+fmt(a.e50,2)],['ATR','$'+fmt(a.atr,2)]].map(x=>`<div class="metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');const sr2=$('signalReadout');if(sr2)sr2.textContent=`AI: ${a.signal} · ${a.score}`}
function drawChart(){const c=$('chart');if(!c)return;const ctx=c.getContext('2d'),dpr=window.devicePixelRatio||1,w=c.clientWidth,h=300;c.width=Math.max(1,w*dpr);c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const k=state.liveKline?[...state.klines.slice(-99),state.liveKline]:state.klines.slice(-100);if(k.length<2)return;const highs=k.map(x=>+x[2]),lows=k.map(x=>+x[3]),max=Math.max(...highs),min=Math.min(...lows),pad={t:14,b:28,l:8,r:58},cw=(w-pad.l-pad.r)/k.length,range=max-min||1;ctx.font='9px Cairo';ctx.strokeStyle='#1c201d';ctx.lineWidth=1;for(let j=0;j<5;j++){const y=pad.t+j*(h-pad.t-pad.b)/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillStyle='#666c75';ctx.fillText('$'+fmt(max-j*range/4,2),w-pad.r+5,y+3)}const vh=Math.max(...k.map(x=>+x[5]));k.forEach((x,i)=>{const o=+x[1],hi=+x[2],lo=+x[3],cl=+x[4],cx=pad.l+i*cw+cw/2,y=v=>pad.t+(max-v)/range*(h-pad.t-pad.b-40),body=Math.max(2,Math.abs(y(o)-y(cl))),up=cl>=o;ctx.strokeStyle=up?'#43dfa0':'#ff637d';ctx.fillStyle=up?'#43dfa0':'#ff637d';ctx.beginPath();ctx.moveTo(cx,y(hi));ctx.lineTo(cx,y(lo));ctx.stroke();ctx.fillRect(cx-cw*.31,Math.min(y(o),y(cl)),Math.max(2,cw*.62),body);const barH=(+x[5]/vh)*28;ctx.globalAlpha=.22;ctx.fillRect(cx-cw*.31,h-pad.b-barH,Math.max(2,cw*.62),barH);ctx.globalAlpha=1});ctx.fillStyle='#777d87';ctx.fillText(state.liveKline?'LIVE · Binance WebSocket':'100 شمعة مغلقة',8,h-8)}
function notifyUser(title,body){try{if('Notification' in window&&Notification.permission==='granted')new Notification(title,{body});}catch(e){}if(navigator.vibrate)navigator.vibrate([180,80,180])}
function handleSignalAlert(a,current,initial=false){if(initial){state.lastSignal=a.signal;state.pendingSignal=null;state.pendingCount=0;return}if(!state.alertEnabled||a.signal==='انتظار')return;if(a.signal===state.pendingSignal)state.pendingCount++;else{state.pendingSignal=a.signal;state.pendingCount=1}if(state.pendingCount<2||a.signal===state.lastSignal)return;const key=`${state.symbol}|${state.interval}|${a.signal}`;if(state.lastAlertKey===key)return;state.lastAlertKey=key;state.lastSignal=a.signal;const word=a.signal==='شراء'?'شراء الآن':'بيع الآن';notifyUser(`GOLDAN AI · ${word}`,`${state.symbol.replace('USDT','/USDT')} — السعر $${fmt(current,2)} — إشارة مؤكدة على السوق المباشر.`);if($('alertTitle'))$('alertTitle').textContent=`${word} · ${state.symbol.replace('USDT','/USDT')}`;if($('alertText'))$('alertText').textContent=`السعر الحالي $${fmt(current,2)} · إشارة ${a.signal} بعد تأكيد تحديثين متتاليين.`}
async function enableAlerts(){try{if('Notification' in window){const p=await Notification.requestPermission();state.alertEnabled=p==='granted';}else state.alertEnabled=true;}catch(e){state.alertEnabled=true}if($('alertBtn')){$('alertBtn').textContent=state.alertEnabled?'مفعّلة':'إعادة المحاولة';$('alertBtn').disabled=state.alertEnabled}if($('alertText'))$('alertText').textContent=state.alertEnabled?'التنبيهات مفعّلة أثناء تشغيل GOLDAN AI. للتنبيه بعد إغلاق التطبيق يلزم دعم إشعارات Android الأصلية.':'لم تسمح بالإشعارات. فعّلها من إعدادات Android.'}
function refresh(){if(state.loading)return;if($('refreshBtn')){$('refreshBtn').disabled=true;$('refreshBtn').textContent='…'}Promise.all([loadTickers(),loadAnalysis()]).catch(e=>showError(e.message)).finally(()=>{if($('refreshBtn')){$('refreshBtn').disabled=false;$('refreshBtn').textContent='↻'}})}
document.querySelectorAll('.tf').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tf').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.interval=b.dataset.interval;stopLiveStream();state.lastSignal=null;state.lastAlertKey=null;loadAnalysis()});document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderCoins()});$('searchInput').oninput=renderCoins;$('refreshBtn').onclick=refresh;$('alertBtn').onclick=enableAlerts;window.addEventListener('resize',()=>state.klines.length&&drawChart());setInterval(()=>{if(!state.loading)loadTickers().catch(()=>{})},15000);refresh();