/* GOLDAN AI — original TradingView-style chart engine (Binance public data only) */
(()=> {
  'use strict';
  const C=()=>document.getElementById('chart'), P=()=>C()?.closest('.chart-panel');
  const K=()=>state.liveKline?[...state.klines,state.liveKline]:state.klines.slice();
  const S=window.goldanTVState=window.goldanTVState||{
    type:'candle',inds:new Set(),mode:'pan',drawings:[],undo:[],redo:[],compare:null,compareData:null,
    alerts:[],locked:false,hidden:false,magnet:true,crosshair:true,replay:false,replayIndex:null,
    visible:100,first:null,layout:1,settings:{grid:true},lastDraw:null
  };
  const css=`
  .gtv-pop{position:absolute;z-index:10030;top:42px;left:8px;right:8px;max-height:72vh;overflow:auto;background:#07101b;border:1px solid #29476f;border-radius:14px;padding:10px;box-shadow:0 20px 70px #000c;color:#dceaff}
  .gtv-head{display:flex;justify-content:space-between;gap:6px;align-items:center;margin-bottom:8px}.gtv-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}
  .gtv-btn{border:1px solid #23405f;background:#0a1726;color:#a8c8e9;border-radius:8px;padding:7px;font:inherit;font-size:9px}.gtv-btn.on{border-color:#4e96ff;background:#102b4b;color:#fff}
  .gtv-section{margin:10px 0 5px;color:#6eaaff;font-size:9px}.gtv-subpanel{border-top:1px solid #18283d;padding-top:6px;margin-top:6px}
  .gtv-alert{position:absolute;z-index:10040;right:10px;bottom:10px;background:#0a1523;border:1px solid #3b73b8;border-radius:9px;padding:8px;color:#dceaff;font-size:9px}
  .gtv-replay{position:absolute;z-index:10035;left:10px;bottom:10px;display:flex;gap:5px;align-items:center;background:#07101b;border:1px solid #29476f;border-radius:10px;padding:7px}
  .gtv-cross{position:absolute;z-index:10020;pointer-events:none;display:none;border-top:1px dashed #75859a;border-left:1px dashed #75859a}.gtv-cross.on{display:block}
  .gtv-tip{position:absolute;z-index:10041;pointer-events:none;background:#081321;border:1px solid #2d4e76;border-radius:7px;padding:4px 7px;color:#dbeaff;font-size:8px;white-space:nowrap}
  .gtv-hide{display:none!important}.gtv-layout{display:grid;gap:5px}.gtv-layout.l2{grid-template-columns:1fr 1fr}.gtv-layout.l4{grid-template-columns:1fr 1fr}
  `;
  if(!document.getElementById('goldan-tv-engine-style')){const st=document.createElement('style');st.id='goldan-tv-engine-style';st.textContent=css;document.head.appendChild(st)}
  const q=(a,p)=>{const o=Array(a.length).fill(null);let sum=0;for(let i=0;i<a.length;i++){sum+=a[i];if(i>=p)sum-=a[i-p];if(i>=p-1)o[i]=sum/p}return o};
  const ema=(a,p)=>{const o=Array(a.length).fill(null);if(a.length<p)return o;let e=a.slice(0,p).reduce((x,y)=>x+y,0)/p,k=2/(p+1);o[p-1]=e;for(let i=p;i<a.length;i++){e=a[i]*k+e*(1-k);o[i]=e}return o};
  const rsi=a=>{const o=Array(a.length).fill(null),p=14;if(a.length<=p)return o;let g=0,l=0;for(let i=1;i<=p;i++){const d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}let ag=g/p,al=l/p;o[p]=al?100-100/(1+ag/al):100;for(let i=p+1;i<a.length;i++){const d=a[i]-a[i-1];ag=(ag*13+Math.max(d,0))/14;al=(al*13+Math.max(-d,0))/14;o[i]=al?100-100/(1+ag/al):100}return o};
  const macd=a=>{const f=ema(a,12),s=ema(a,26),m=a.map((_,i)=>f[i]!=null&&s[i]!=null?f[i]-s[i]:null),sig=ema(m.map(x=>x??0),9);return[m,sig]};
  const atr=k=>{const tr=k.map((x,i)=>i?Math.max(+x[2]-+x[3],Math.abs(+x[2]-+k[i-1][4]),Math.abs(+x[3]-+k[i-1][4])):+x[2]-+x[3]);return q(tr,14)};
  const boll=a=>{const mid=q(a,20),u=Array(a.length).fill(null),l=Array(a.length).fill(null);for(let i=19;i<a.length;i++){const z=a.slice(i-19,i+1),m=mid[i],sd=Math.sqrt(z.reduce((s,v)=>s+(v-m)**2,0)/20);u[i]=m+2*sd;l[i]=m-2*sd}return[mid,u,l]};
  const vwap=k=>{let pv=0,v=0;return k.map(z=>{const p=(+z[2]+ +z[3]+ +z[4])/3;v+=+z[5];pv+=p*+z[5];return v?pv/v:null})};
  const fmtP=v=>{try{return Number(v).toLocaleString('en-US',{maximumFractionDigits:v>=100?2:v>=1?4:6})}catch(_){return String(v)}};
  function snapshot(){return JSON.stringify({type:S.type,inds:[...S.inds],mode:S.mode,drawings:S.drawings,hidden:S.hidden,locked:S.locked,magnet:S.magnet})}
  function saveHistory(){S.undo.push(snapshot());if(S.undo.length>60)S.undo.shift();S.redo=[]}
  function restore(raw){try{const x=JSON.parse(raw);S.type=x.type;S.inds=new Set(x.inds||[]);S.drawings=x.drawings||[];S.hidden=!!x.hidden;S.locked=!!x.locked;S.magnet=x.magnet!==false;render()}catch(_){}}
  function menu(title,body){const p=P();if(!p)return null;p.querySelectorAll('.gtv-pop').forEach(x=>x.remove());const m=document.createElement('div');m.className='gtv-pop';m.innerHTML='<div class="gtv-head"><b>'+title+'</b><button class="gtv-btn" data-close>✕</button></div>'+body;p.appendChild(m);m.querySelector('[data-close]').onclick=()=>m.remove();return m}
  function indicators(){const names=[['sma20','SMA 20'],['sma50','SMA 50'],['ema20','EMA 20'],['ema50','EMA 50'],['bb','Bollinger Bands'],['vwap','VWAP'],['volume','Volume'],['rsi','RSI 14'],['macd','MACD'],['atr','ATR 14']];const m=menu('المؤشرات والنوافذ الفرعية','<div class="gtv-grid">'+names.map(x=>'<button class="gtv-btn '+(S.inds.has(x[0])?'on':'')+'" data-i="'+x[0]+'">'+x[1]+'</button>').join('')+'</div><div class="gtv-section">RSI / MACD / ATR تظهر في نوافذ مستقلة أسفل الرسم.</div>');m?.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{saveHistory();const i=b.dataset.i;S.inds.has(i)?S.inds.delete(i):S.inds.add(i);b.classList.toggle('on',S.inds.has(i));render()})}
  function chartTypes(){const types=[['candle','شموع'],['hollow','شموع مجوفة'],['line','خط'],['area','منطقة'],['bar','OHLC Bars'],['heikin','Heikin Ashi'],['baseline','Baseline'],['columns','أعمدة']];const m=menu('أنواع الرسم','<div class="gtv-grid">'+types.map(x=>'<button class="gtv-btn '+(S.type===x[0]?'on':'')+'" data-t="'+x[0]+'">'+x[1]+'</button>').join('')+'</div><small style="display:block;margin-top:9px;color:#71839a">الأنواع المتقدمة المعتمدة على بيانات خاصة غير متاحة هنا لا يتم تزويرها.</small>');m?.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{saveHistory();S.type=b.dataset.t;m.remove();render()})}
  function drawings(){const ds=[['pan','المؤشر'],['line','خط اتجاه'],['ray','Ray'],['h','أفقي'],['v','عمودي'],['channel','قناة'],['rect','مستطيل'],['circle','دائرة'],['fib','Fibonacci Retracement'],['fibext','Fib Extension'],['measure','قياس'],['text','نص']];const m=menu('أدوات الرسم + Magnet','<div class="gtv-grid">'+ds.map(x=>'<button class="gtv-btn '+(S.mode===x[0]?'on':'')+'" data-d="'+x[0]+'">'+x[1]+'</button>').join('')+'</div><div class="gtv-subpanel"><div class="gtv-grid"><button class="gtv-btn '+(S.magnet?'on':'')+'" data-d="magnet">🧲 Magnet</button><button class="gtv-btn '+(S.hidden?'on':'')+'" data-d="hide">إخفاء الرسومات</button><button class="gtv-btn" data-d="undo">↶ تراجع</button><button class="gtv-btn" data-d="redo">↷ إعادة</button><button class="gtv-btn" data-d="clear">مسح الكل</button></div></div>');m?.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{const d=b.dataset.d;if(d==='magnet'){S.magnet=!S.magnet;render();return}if(d==='hide'){S.hidden=!S.hidden;m.remove();render();return}if(d==='undo'){undo();m.remove();return}if(d==='redo'){redo();m.remove();return}if(d==='clear'){saveHistory();S.drawings=[];m.remove();render();return}saveHistory();S.mode=d;m.remove();if(C())C().style.cursor=d==='pan'?'grab':'crosshair'})}
  function compare(){const syms=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','ADAUSDT','DOGEUSDT','AVAXUSDT'];const m=menu('مقارنة حقيقية من Binance','<div class="gtv-grid">'+syms.map(x=>'<button class="gtv-btn '+(S.compare===x?'on':'')+'" data-s="'+x+'">'+x+'</button>').join('')+'</div><button class="gtv-btn" data-clear style="margin-top:7px;width:100%">إزالة المقارنة</button>');m?.querySelectorAll('[data-s]').forEach(b=>b.onclick=async()=>{S.compare=b.dataset.s;m.remove();await loadCompare();render()});m?.querySelector('[data-clear]')?.addEventListener('click',()=>{S.compare=null;S.compareData=null;m.remove();render()})}
  async function loadCompare(){if(!S.compare)return;try{const int=state.interval||'15m',u='https://api.binance.com/api/v3/klines?symbol='+S.compare+'&interval='+int+'&limit=500',r=await fetch(u);if(!r.ok)throw Error();S.compareData=await r.json()}catch(_){S.compareData=null;toast('تعذر تحميل المقارنة من Binance')}} 
  function alertMenu(){const m=menu('التنبيهات','<div class="gtv-grid"><button class="gtv-btn" data-a="above">السعر أعلى من</button><button class="gtv-btn" data-a="below">السعر أقل من</button><button class="gtv-btn" data-a="cross">يعبر السعر</button><button class="gtv-btn" data-a="signal">إشارة GOLDAN</button></div><input id="gtvAlertPrice" inputmode="decimal" placeholder="السعر" style="width:100%;box-sizing:border-box;margin-top:8px;background:#0a1726;border:1px solid #29476f;border-radius:8px;padding:8px;color:#fff"><small style="display:block;margin-top:7px;color:#71839a">التنبيه المحلي يعمل أثناء تشغيل التطبيق؛ لا يوجد ادعاء بتنبيه بعد إغلاقه دون Push أصلي.</small>');m?.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{const type=b.dataset.a,price=+m.querySelector('#gtvAlertPrice')?.value;if(type!=='signal'&&!(price>0)){toast('أدخل السعر أولاً');return}S.alerts.push({type,price,armed:true,last:state.lastPrice||0});toast('تم حفظ التنبيه');})}
  function toast(msg){const p=P();if(!p)return;const n=document.createElement('div');n.className='gtv-alert';n.textContent=msg;p.appendChild(n);setTimeout(()=>n.remove(),3000)}
  function checkAlerts(){const p=state.lastPrice||+K().at(-1)?.[4]||0;S.alerts=S.alerts.filter(a=>{let hit=false;if(a.type==='above')hit=p>=a.price;if(a.type==='below')hit=p<=a.price;if(a.type==='cross')hit=(a.last<a.price&&p>=a.price)||(a.last>a.price&&p<=a.price);if(a.type==='signal')hit=state.lastSignal==='شراء'||state.lastSignal==='بيع';a.last=p;if(hit){toast('🔔 تنبيه GOLDAN · '+fmtP(p));try{if(Notification?.permission==='granted')new Notification('GOLDAN AI',{body:'تنبيه عند $'+fmtP(p)})}catch(_){}return false}return true})}
  function undo(){if(!S.undo.length)return;S.redo.push(snapshot());restore(S.undo.pop())}
  function redo(){if(!S.redo.length)return;S.undo.push(snapshot());restore(S.redo.pop())}
  function range(){const c=C(),k=K();if(!c||k.length<2)return null;const n=k.length,w=c.clientWidth,h=Math.max(330,c.clientHeight||330),left=8,right=68,top=12,bottom=h-14;S.visible=Math.max(35,Math.min(180,S.visible));if(S.first==null)S.first=Math.max(0,n-S.visible);S.first=Math.max(0,Math.min(Math.max(0,n-S.visible),S.first));const count=Math.min(S.visible,n),part=k.slice(S.first,S.first+count);let hi=Math.max(...part.map(x=>+x[2])),lo=Math.min(...part.map(x=>+x[3]));return{c,k,n,w,h,left,right,top,bottom,count,first:S.first,part,hi,lo,step:(w-left-right)/count}}
  function magnetPrice(i,p,k){if(!S.magnet)return p;const z=k[Math.max(0,Math.min(k.length-1,i))];return [+z[1],+z[2],+z[3],+z[4]].reduce((best,v)=>Math.abs(v-p)<Math.abs(best-p)?v:best,p)}
  function drawCandles(ctx,R,y,x){const {part,step}=R;const he=[];for(let i=0;i<part.length;i++){const z=part[i],o=+z[1],h=+z[2],l=+z[3],c=+z[4];if(i===0)he.push([o,h,l,c]);else{const p=he[i-1],hc=(o+h+l+c)/4,ho=(p[0]+p[3])/2;he.push([ho,Math.max(h,ho,hc),Math.min(l,ho,hc),hc])}}
    part.forEach((z,i)=>{let o=+z[1],h=+z[2],l=+z[3],c=+z[4];if(S.type==='heikin')[o,h,l,c]=he[i];const xx=x(R.first+i),up=c>=o,col=up?'#43dfa0':'#ff637d';ctx.strokeStyle=col;ctx.fillStyle=col;ctx.lineWidth=1;if(S.type==='bar'){ctx.beginPath();ctx.moveTo(xx,y(h));ctx.lineTo(xx,y(l));ctx.moveTo(xx-5,y(o));ctx.lineTo(xx,y(o));ctx.moveTo(xx,y(c));ctx.lineTo(xx+5,y(c));ctx.stroke()}else if(S.type==='columns'){ctx.fillRect(xx-step*.3,y(c),step*.6,R.bottom-y(c))}else{ctx.beginPath();ctx.moveTo(xx,y(h));ctx.lineTo(xx,y(l));ctx.stroke();if(S.type==='hollow'&&up){ctx.strokeRect(xx-Math.max(2,step*.55)/2,Math.min(y(o),y(c)),Math.max(2,step*.55),Math.max(2,Math.abs(y(o)-y(c))))}else ctx.fillRect(xx-Math.max(2,step*.55)/2,Math.min(y(o),y(c)),Math.max(2,step*.55),Math.max(2,Math.abs(y(o)-y(c))))}})}
  function drawOverlays(ctx,R,y,x){const a=R.k.map(z=>+z[4]);const arr=[];for(const i of S.inds){if(i==='sma20')arr.push(['SMA20',q(a,20)]);if(i==='sma50')arr.push(['SMA50',q(a,50)]);if(i==='ema20')arr.push(['EMA20',ema(a,20)]);if(i==='ema50')arr.push(['EMA50',ema(a,50)]);if(i==='bb'){const b=boll(a);arr.push(['BBU',b[1]],['BBL',b[2]])}if(i==='vwap')arr.push(['VWAP',vwap(R.k)])}for(const [name,z] of arr){ctx.strokeStyle=name==='VWAP'?'#f0c86a':name.startsWith('BB')?'#8a9cff':'#2f8cff';ctx.lineWidth=1.5;ctx.beginPath();let on=false;for(let i=R.first;i<R.first+R.count;i++){if(z[i]==null)continue;const xx=x(i),yy=y(z[i]);if(!on){ctx.moveTo(xx,yy);on=true}else ctx.lineTo(xx,yy)}if(on)ctx.stroke()}}
  function panels(ctx,R,y,x){const k=R.k,a=k.map(z=>+z[4]);const sets=[];if(S.inds.has('rsi'))sets.push(['RSI',rsi(a),0,100]);if(S.inds.has('macd')){const m=macd(a);sets.push(['MACD',m[0],null,null],['SIGNAL',m[1],null,null])}if(S.inds.has('atr'))sets.push(['ATR',atr(k),null,null]);if(!sets.length)return;const ph=Math.min(75,Math.max(52,(R.bottom-R.top)*.18));let py=R.bottom-ph*sets.length;sets.forEach((z,n)=>{ctx.strokeStyle='#202a39';ctx.beginPath();ctx.moveTo(R.left,py);ctx.lineTo(R.w-R.right,py);ctx.stroke();const vals=z[1].slice(R.first,R.first+R.count).filter(v=>v!=null),mx=z[3]??Math.max(...vals,1),mn=z[2]??Math.min(...vals,0),rg=mx-mn||1;ctx.strokeStyle=n?'#5bb7ff':'#c18cff';ctx.beginPath();let on=false;for(let i=R.first;i<R.first+R.count;i++){const v=z[1][i];if(v==null)continue;const xx=x(i),yy=py+ph-8-(v-mn)/rg*(ph-16);if(!on){ctx.moveTo(xx,yy);on=true}else ctx.lineTo(xx,yy)}if(on)ctx.stroke();ctx.fillStyle='#75869a';ctx.font='8px Cairo';ctx.fillText(z[0],R.left+4,py+11);if(z[0]==='RSI'){ctx.strokeStyle='#39475a';[30,70].forEach(v=>{const yy=py+ph-(v/100)*ph;ctx.beginPath();ctx.moveTo(R.left,yy);ctx.lineTo(R.w-R.right,yy);ctx.stroke()})}py+=ph})}
  function drawDrawings(ctx,R,hi,lo){if(S.hidden)return;const y=v=>R.top+(hi-v)/(hi-lo)*(R.bottom-R.top),x=i=>R.left+(i-R.first+.5)*R.step;ctx.save();ctx.strokeStyle='#f3c95e';ctx.fillStyle='#f3c95e';ctx.lineWidth=1.4;for(const z of S.drawings){const x1=x(z.i1),x2=x(z.i2),y1=y(z.p1),y2=y(z.p2);if(z.type==='h'){ctx.beginPath();ctx.moveTo(R.left,y1);ctx.lineTo(R.w-R.right,y1);ctx.stroke()}else if(z.type==='v'){ctx.beginPath();ctx.moveTo(x1,R.top);ctx.lineTo(x1,R.bottom);ctx.stroke()}else if(z.type==='rect'){ctx.strokeRect(Math.min(x1,x2),Math.min(y1,y2),Math.abs(x2-x1),Math.abs(y2-y1))}else if(z.type==='circle'){ctx.beginPath();ctx.ellipse((x1+x2)/2,(y1+y2)/2,Math.abs(x2-x1)/2,Math.abs(y2-y1)/2,0,0,Math.PI*2);ctx.stroke()}else if(z.type==='channel'){const dy=y2-y1;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.moveTo(x1,y1+dy*.35);ctx.lineTo(x2,y2+dy*.35);ctx.stroke()}else if(z.type==='fib'||z.type==='fibext'){const d=z.p2-z.p1,lv=z.type==='fibext'?[0,.272,.382,.5,.618,1,1.272,1.618,2.618]:[0,.236,.382,.5,.618,.786,1];lv.forEach(v=>{const yy=y(z.p1+d*v);ctx.beginPath();ctx.moveTo(R.left,yy);ctx.lineTo(R.w-R.right,yy);ctx.stroke();ctx.fillText((v*100).toFixed(1)+'%',R.left+4,yy-2)})}else if(z.type==='text'){ctx.fillText(z.text||'GOLDAN',x1,y1)}else{ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);if(z.type==='ray'){ctx.lineTo(x2+(x2-x1)*5,y2+(y2-y1)*5)}ctx.stroke();if(z.type==='measure')ctx.fillText((z.p2-z.p1).toFixed(4)+' · '+Math.abs(z.i2-z.i1)+' bars',x2,y2-4)}}ctx.restore()}
  function compareLine(ctx,R,y,x){if(!S.compareData?.length)return;const base=+S.compareData[0][4]||1;ctx.strokeStyle='#c17cff';ctx.lineWidth=1.7;ctx.beginPath();let on=false;for(let i=R.first;i<Math.min(R.first+R.count,S.compareData.length);i++){const v=(+S.compareData[i][4]/base-1)*100;const xx=x(i),yy=R.top+(0.5-v/10)*(R.bottom-R.top);if(!on){ctx.moveTo(xx,yy);on=true}else ctx.lineTo(xx,yy)}if(on)ctx.stroke();ctx.fillStyle='#c17cff';ctx.font='8px Cairo';ctx.fillText('COMPARE '+S.compare,R.left+6,R.top+12)}
  function render(){const R=range();if(!R)return;const c=R.c,ctx=c.getContext('2d'),d=devicePixelRatio||1;c.width=R.w*d;c.height=R.h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,R.w,R.h);let hi=R.hi,lo=R.lo;const a=R.k.map(z=>+z[4]);for(let i=R.first;i<R.first+R.count;i++){for(const z of [q(a,20),q(a,50),ema(a,20),ema(a,50)])if(z[i]!=null){hi=Math.max(hi,z[i]);lo=Math.min(lo,z[i])}}const pad=(hi-lo||1)*.08;hi+=pad;lo-=pad;const y=v=>R.top+(hi-v)/(hi-lo)*(R.bottom-R.top),x=i=>R.left+(i-R.first+.5)*R.step;ctx.font='9px Cairo';if(S.settings.grid){for(let j=0;j<6;j++){const yy=R.top+j*(R.bottom-R.top)/5;ctx.strokeStyle='#171f2a';ctx.beginPath();ctx.moveTo(R.left,yy);ctx.lineTo(R.w-R.right,yy);ctx.stroke();ctx.fillStyle='#707887';ctx.fillText(fmtP(hi-j*(hi-lo)/5),R.w-R.right+5,yy+3)}}if(S.type==='line'||S.type==='area'||S.type==='baseline'){ctx.strokeStyle='#6fb2ff';ctx.lineWidth=2;ctx.beginPath();R.part.forEach((z,i)=>{const xx=x(R.first+i),yy=y(+z[4]);i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.stroke();if(S.type==='area'){ctx.lineTo(x(R.first+R.part.length-1),R.bottom);ctx.lineTo(x(R.first),R.bottom);ctx.closePath();ctx.globalAlpha=.12;ctx.fillStyle='#3b8cff';ctx.fill();ctx.globalAlpha=1}if(S.type==='baseline'){ctx.setLineDash([4,3]);ctx.strokeStyle='#667384';ctx.beginPath();ctx.moveTo(R.left,y((hi+lo)/2));ctx.lineTo(R.w-R.right,y((hi+lo)/2));ctx.stroke();ctx.setLineDash([])}}else drawCandles(ctx,R,y,x);drawOverlays(ctx,R,y,x);if(S.inds.has('volume')){const mv=Math.max(...R.part.map(z=>+z[5]))||1;R.part.forEach((z,i)=>{ctx.globalAlpha=.18;ctx.fillStyle=+z[4]>=+z[1]?'#43dfa0':'#ff637d';ctx.fillRect(x(R.first+i)-R.step*.28,R.bottom-(+z[5]/mv)*28,R.step*.56,(+z[5]/mv)*28);ctx.globalAlpha=1})}panels(ctx,R,y,x);drawDrawings(ctx,R,hi,lo);compareLine(ctx,R,y,x);const cp=state.lastPrice||+R.k.at(-1)[4];ctx.setLineDash([5,4]);ctx.strokeStyle='#87a8cf';ctx.globalAlpha=.65;ctx.beginPath();ctx.moveTo(R.left,y(cp));ctx.lineTo(R.w-R.right,y(cp));ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;ctx.fillStyle='#8bb8f2';ctx.fillText((S.compare?'COMPARE '+S.compare+' · ':'')+'LIVE · Binance',R.left,R.h-5);checkAlerts();legend()}
  function legend(){const e=document.getElementById('indicatorLegend');if(e)e.textContent=S.inds.size?'ƒx '+[...S.inds].join(' · '):'ƒx لا توجد مؤشرات';const l=document.getElementById('chartModeLabel');if(l)l.textContent='الرسم: '+S.type+(S.replay?' · REPLAY':'')}
  function point(ev,R){const rr=C().getBoundingClientRect(),px=ev.clientX-rr.left,py=ev.clientY-rr.top;let i=Math.round(R.first+(px-R.left)/R.step-.5);i=Math.max(0,Math.min(R.n-1,i));let p=R.hi-(py-R.top)/(R.bottom-R.top)*(R.hi-R.lo);p=magnetPrice(i,p,R.k);return{i,p}}
  function bindCanvas(){const c=C();if(!c||c.dataset.gtvEngine)return;c.dataset.gtvEngine='1';let down=null,lastX=0;const cross=document.createElement('div');cross.className='gtv-cross';c.parentElement?.appendChild(cross);const tip=document.createElement('div');tip.className='gtv-tip';tip.style.display='none';c.parentElement?.appendChild(tip);
    c.addEventListener('pointerdown',e=>{if(S.locked)return;lastX=e.clientX;if(S.mode!=='pan'){down=point(e,range());return}c.setPointerCapture(e.pointerId)});
    c.addEventListener('pointermove',e=>{const R=range();if(!R)return;const rr=c.getBoundingClientRect(),px=e.clientX-rr.left,py=e.clientY-rr.top;if(S.crosshair){cross.classList.add('on');cross.style.left=px+'px';cross.style.top=py+'px';cross.style.width=Math.max(0,c.clientWidth-px)+'px';cross.style.height=Math.max(0,c.clientHeight-py)+'px';const pt=point(e,R),z=R.k[pt.i];tip.style.display='block';tip.style.left=Math.min(c.clientWidth-120,px+8)+'px';tip.style.top=Math.max(4,py-24)+'px';tip.textContent=z?('O '+fmtP(+z[1])+' H '+fmtP(+z[2])+' L '+fmtP(+z[3])+' C '+fmtP(+z[4])):''}
      if(S.mode==='pan'&&e.buttons){const dx=e.clientX-lastX;lastX=e.clientX;S.first-=Math.round(dx/Math.max(1,R.step));S.first=Math.max(0,Math.min(R.n-R.visible,S.first));render()}});
    c.addEventListener('pointerup',e=>{if(!down||S.mode==='pan')return;const R=range();if(!R)return;const b=point(e,R),m=S.mode;saveHistory();if(['h','v'].includes(m))S.drawings.push({type:m,i1:b.i,i2:b.i,p1:b.p,p2:b.p});else if(m==='text'){const t=prompt('اكتب النص:','GOLDAN');if(t)S.drawings.push({type:m,i1:b.i,i2:b.i,p1:b.p,p2:b.p,text:t})}else S.drawings.push({type:m,i1:down.i,i2:b.i,p1:down.p,p2:b.p});down=null;S.mode='pan';c.style.cursor='grab';render()});
    c.addEventListener('pointerleave',()=>{cross.classList.remove('on');tip.style.display='none'});c.addEventListener('wheel',e=>{e.preventDefault();S.visible=Math.max(35,Math.min(180,Math.round(S.visible*(e.deltaY>0?1.12:.89))));const R=range();if(R)S.first=Math.max(0,Math.min(R.n-S.visible,R.first));render()},{passive:false});c.addEventListener('dblclick',()=>toggleFullscreen())}
  function toggleFullscreen(){const p=P();if(!p)return;p.classList.toggle('chart-fullscreen');setTimeout(render,30)}
  function replayMenu(){const p=P();if(!p)return;S.replay=!S.replay;if(S.replay){S.replayIndex=Math.max(40,K().length-1);S.mode='pan';showReplayControls()}else{p.querySelector('.gtv-replay')?.remove();S.replayIndex=null}render()}
  function showReplayControls(){const p=P();if(!p)return;p.querySelector('.gtv-replay')?.remove();const d=document.createElement('div');d.className='gtv-replay';d.innerHTML='<button class="gtv-btn" data-r="step">▶ خطوة</button><button class="gtv-btn" data-r="play">⏵ تشغيل</button><button class="gtv-btn" data-r="stop">■ خروج</button><span style="color:#8193aa;font-size:8px">Replay</span>';p.appendChild(d);let timer=null;d.onclick=e=>{const a=e.target.dataset.r;if(a==='step'){S.replayIndex=Math.min(K().length-1,(S.replayIndex??40)+1);render()}if(a==='play'){clearInterval(timer);timer=setInterval(()=>{if(!S.replay){clearInterval(timer);return}S.replayIndex=Math.min(K().length-1,(S.replayIndex??40)+1);render();if(S.replayIndex>=K().length-1)clearInterval(timer)},450)}if(a==='stop'){clearInterval(timer);S.replay=false;S.replayIndex=null;d.remove();render()}}}
  function layoutMenu(){const m=menu('التخطيطات','<div class="gtv-grid"><button class="gtv-btn" data-l="1">1 Chart</button><button class="gtv-btn" data-l="2">2 Charts</button><button class="gtv-btn" data-l="4">4 Charts</button></div><small style="display:block;margin-top:8px;color:#71839a">كل تخطيط يحفظ إعداداته محليًا. الرسوم المتعددة تستخدم نفس بيانات السوق الحالية.</small>');m?.querySelectorAll('[data-l]').forEach(b=>b.onclick=()=>{S.layout=+b.dataset.l;localStorage.setItem('goldanLayoutGrid',String(S.layout));m.remove();toast('تم اختيار تخطيط '+S.layout+' Chart');render()})}
  function wire(){document.getElementById('chartTypeBtn')?.addEventListener('click',chartTypes);document.getElementById('indicatorBtn')?.addEventListener('click',indicators);document.getElementById('drawingBtn')?.addEventListener('click',drawings);document.getElementById('compareBtn')?.addEventListener('click',compare);document.getElementById('chartAlertBtn')?.addEventListener('click',alertMenu);document.getElementById('layoutBtn')?.addEventListener('click',layoutMenu);document.getElementById('replayBtn')?.addEventListener('click',replayMenu);document.getElementById('undoBtn')?.addEventListener('click',undo);document.getElementById('redoBtn')?.addEventListener('click',redo);document.getElementById('hideBtn')?.addEventListener('click',()=>{S.hidden=!S.hidden;render()});document.getElementById('lockBtn')?.addEventListener('click',()=>{S.locked=!S.locked;toast(S.locked?'تم قفل الرسومات':'تم فتح الرسومات')});document.getElementById('settingsBtn')?.addEventListener('click',()=>{const m=menu('إعدادات الرسم','<div class="gtv-grid"><button class="gtv-btn '+(S.settings.grid?'on':'')+'" data-g="grid">الشبكة</button><button class="gtv-btn '+(S.crosshair?'on':'')+'" data-g="cross">Crosshair</button><button class="gtv-btn '+(S.magnet?'on':'')+'" data-g="magnet">Magnet</button></div>');m?.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>{const g=b.dataset.g;if(g==='grid')S.settings.grid=!S.settings.grid;if(g==='cross')S.crosshair=!S.crosshair;if(g==='magnet')S.magnet=!S.magnet;b.classList.toggle('on');render()})});document.getElementById('saveLayoutBtn')?.addEventListener('click',()=>{localStorage.setItem('goldanTVLayout',snapshot());toast('تم حفظ التخطيط والمؤشرات والرسومات')});document.getElementById('quickSearchBtn')?.addEventListener('click',quickSearch);document.getElementById('favoriteBtn')?.addEventListener('click',e=>e.currentTarget.classList.toggle('active'));bindCanvas();const saved=localStorage.getItem('goldanTVLayout');if(saved)restore(saved)}
  function quickSearch(){const q=prompt('بحث سريع: SMA, RSI, MACD, Fibonacci, خط, مستطيل, Magnet, Replay, BTCUSDT');if(!q)return;const z=q.toLowerCase();if(z.includes('rsi')){S.inds.add('rsi');render()}else if(z.includes('macd')){S.inds.add('macd');render()}else if(z.includes('sma')){S.inds.add('sma20');render()}else if(z.includes('fibo')){S.mode='fib';toast('اختر نقطتين على الرسم')}else if(z.includes('magnet')){S.magnet=!S.magnet;toast('Magnet '+(S.magnet?'مفعل':'متوقف'))}else if(z.includes('replay'))replayMenu();else if(z.includes('btc')){const inp=document.getElementById('searchInput');if(inp){inp.value='BTC';inp.dispatchEvent(new Event('input',{bubbles:true}))}}}
  function renderSafe(){try{render()}catch(e){console.error('GOLDAN chart',e)}}
  window.goldanTradingViewRender=renderSafe;window.goldanTVState=S;window.drawChart=renderSafe;
  wire();setTimeout(renderSafe,80);setInterval(renderSafe,1500);
})();