/* GOLDAN AI — clean live chart + single blue trend line + trade plan + free chart-image analyzer */
(function(){
  const css=`
  .chart-panel{position:relative;overflow:hidden}
  .chart-panel.chart-fullscreen{position:fixed;inset:0;z-index:9999;margin:0;border-radius:0;padding:12px;background:#05070d;overflow:auto}
  .chart-fullscreen canvas{height:calc(100vh - 150px)!important;min-height:360px}
  #chart{touch-action:none;cursor:grab}
  #chart.chart-dragging{cursor:grabbing}
  .chart-tools{display:flex;gap:6px;align-items:center;margin-top:8px;flex-wrap:wrap}
  .chart-tool{border:1px solid #243f75;background:#09111f;color:#6fb2ff;border-radius:9px;padding:7px 10px;font-family:inherit;font-size:9px;cursor:pointer}
  .chart-tool:hover{background:#0d1a2e}
  .chart-hint{color:#646b78;font-size:8px;margin-right:auto}
  .goldan-plan-overlay{position:absolute;left:12px;top:14px;z-index:3;display:flex;gap:5px;flex-wrap:wrap;pointer-events:none}
  .goldan-plan-chip{background:rgba(5,9,16,.9);border:1px solid #203b67;border-radius:8px;padding:4px 7px;color:#a8c9f5;font-size:8px}
  .goldan-ai-modal{position:fixed;inset:0;z-index:10050;background:rgba(2,5,10,.82);display:none;align-items:center;justify-content:center;padding:14px}
  .goldan-ai-modal.open{display:flex}
  .goldan-ai-box{width:min(680px,100%);max-height:92vh;overflow:auto;background:#080d16;border:1px solid #23416d;border-radius:20px;padding:18px;box-shadow:0 24px 80px #000b;color:#eaf2ff}
  .goldan-ai-head{display:flex;align-items:center;justify-content:space-between;gap:10px}
  .goldan-ai-head h3{margin:0;font-size:18px}.goldan-ai-head small{color:#74839a}
  .goldan-ai-close{border:1px solid #263b59;background:#0c1421;color:#b9c8dc;border-radius:9px;padding:6px 10px}
  .goldan-ai-drop{margin-top:14px;border:1px dashed #31527f;border-radius:14px;padding:18px;text-align:center;color:#93a7c2}
  .goldan-ai-drop input{display:block;width:100%;margin-top:10px}
  .goldan-ai-preview{display:none;width:100%;max-height:280px;object-fit:contain;border-radius:12px;margin-top:12px;background:#03060b}
  .goldan-ai-actions{display:flex;gap:7px;margin-top:10px;flex-wrap:wrap}
  .goldan-ai-btn{border:1px solid #315a92;background:#0c1b31;color:#9ac7ff;border-radius:9px;padding:8px 12px;font-family:inherit;font-size:9px}
  .goldan-ai-result{margin-top:13px;border:1px solid #1d304b;border-radius:13px;padding:13px;background:#0a111c;line-height:1.9;font-size:10px}
  .goldan-ai-result b{color:#8dc1ff}.goldan-ai-warning{color:#7e8da1;font-size:8px;margin-top:10px;line-height:1.8}
  `;
  const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
  const c=()=>document.getElementById('chart'), panel=()=>c()&&c().closest('.chart-panel');
  const view={start:null,count:90,yShift:0,drag:false,lastX:0,lastY:0};
  function data(){return state.liveKline?[...state.klines.slice(0,-1),state.liveKline]:state.klines.slice()}
  function sma(v,p){const o=Array(v.length).fill(null);let s=0;for(let i=0;i<v.length;i++){s+=v[i];if(i>=p)s-=v[i-p];if(i>=p-1)o[i]=s/p}return o}
  function clamp(n){view.count=Math.max(25,Math.min(180,view.count));view.start=Math.max(0,Math.min(Math.max(0,n-view.count),view.start==null?Math.max(0,n-view.count):view.start))}
  function fmtP(v){return v>=10000?fmt(v,2):v>=100?fmt(v,2):v>=1?fmt(v,4):fmt(v,6)}
  function drawLine(ctx,arr,first,step,y,top,bottom,lo,hi){
    ctx.strokeStyle='#2f8cff';ctx.lineWidth=2.4;ctx.beginPath();let started=false;
    for(let i=first;i<Math.min(arr.length,first+view.count);i++){const v=arr[i];if(v==null)continue;const x=8+(i-first+.5)*step,yy=y(v);if(!started){ctx.moveTo(x,yy);started=true}else ctx.lineTo(x,yy)}
    if(started)ctx.stroke();
  }
  function plan(){const p=state.lastPrice||(+state.klines.at(-1)?.[4]||0),a=typeof analyze==='function'?analyze(data()):null;if(!p||!a)return null;const dir=a.signal==='شراء'?1:a.signal==='بيع'?-1:0;const atr=a.atr||p*.003;return{signal:a.signal,entry:p,stop:dir?p-dir*atr*1.4:null,tp1:dir?p+dir*atr*2:null,tp2:dir?p+dir*atr*3.2:null,score:a.score}}
  function draw(){
    const canvas=c();if(!canvas||!state||!state.klines.length)return;const ctx=canvas.getContext('2d'),dpr=devicePixelRatio||1,w=Math.max(1,canvas.clientWidth),h=Math.max(320,canvas.clientHeight||320);
    canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);
    const all=data(),n=all.length;clamp(n);const first=view.start,last=Math.min(n,first+view.count),k=all.slice(first,last);if(k.length<2)return;
    const closes=all.map(x=>+x[4]),trend=sma(closes,21);let hi=Math.max(...k.map(x=>+x[2])),lo=Math.min(...k.map(x=>+x[3]));
    for(let i=first;i<last;i++)if(trend[i]!=null){hi=Math.max(hi,trend[i]);lo=Math.min(lo,trend[i])}
    const extra=(hi-lo||1)*.08;hi+=extra;lo-=extra;const left=8,right=62,top=16,bottom=h-58,range=hi-lo,cw=(w-left-right)/k.length,y=v=>top+(hi-v)/range*(bottom-top-34);
    ctx.font='10px Cairo';
    for(let j=0;j<6;j++){const yy=top+j*(bottom-top)/5;ctx.strokeStyle='#171c23';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(w-right,yy);ctx.stroke();ctx.fillStyle='#707887';ctx.fillText('$'+fmtP(hi-j*range/5),w-right+5,yy+3)}
    const vh=Math.max(...k.map(x=>+x[5]))||1;
    k.forEach((x,i)=>{const o=+x[1],hh=+x[2],ll=+x[3],cl=+x[4],cx=left+i*cw+cw/2,up=cl>=o,col=up?'#43dfa0':'#ff637d';ctx.strokeStyle=col;ctx.fillStyle=col;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(cx,y(hh));ctx.lineTo(cx,y(ll));ctx.stroke();ctx.fillRect(cx-Math.max(2,cw*.56)/2,Math.min(y(o),y(cl)),Math.max(2,cw*.56),Math.max(2,Math.abs(y(o)-y(cl))));const bh=(+x[5]/vh)*28;ctx.globalAlpha=.18;ctx.fillRect(cx-cw*.28,h-39-bh,Math.max(2,cw*.56),bh);ctx.globalAlpha=1});
    // ONE indicator only: live adaptive blue trend line
    drawLine(ctx,trend,first,cw,y,top,bottom,lo,hi);
    const current=state.lastPrice||+all[n-1][4],py=y(current);ctx.setLineDash([5,4]);ctx.strokeStyle='#8a95a5';ctx.globalAlpha=.45;ctx.beginPath();ctx.moveTo(left,py);ctx.lineTo(w-right,py);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;
    ctx.fillStyle='#dce8f8';ctx.beginPath();ctx.arc(left+(k.length-.5)*cw,y(+k[k.length-1][4]),3.5,0,Math.PI*2);ctx.fill();
    const pl=plan();if(pl&&pl.signal!=='انتظار'){const vals=[['ENTRY',pl.entry],['SL',pl.stop],['TP1',pl.tp1],['TP2',pl.tp2]];ctx.font='8px Cairo';vals.forEach((q,idx)=>{if(q[1]==null)return;const yy=y(q[1]);ctx.setLineDash([3,4]);ctx.strokeStyle=idx===1?'#ff637d':idx>1?'#43dfa0':'#6faeff';ctx.globalAlpha=.6;ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(w-right,yy);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;ctx.fillStyle=idx===1?'#ff8295':idx>1?'#66e4aa':'#82b8ff';ctx.fillText(q[0]+' '+fmtP(q[1]),left+5,yy-3)})}
    ctx.font='8px Cairo';ctx.fillStyle='#6f7886';ctx.fillText('● الأزرق = خط GOLDAN Trend · LIVE Binance',left,h-24);ctx.fillText(`${k.length} شمعة · اسحب للتحريك · قرّب/بعّد`,left,h-9);
  }
  function refreshOverlay(){const p=panel();if(!p)return;let o=p.querySelector('.goldan-plan-overlay');if(!o){o=document.createElement('div');o.className='goldan-plan-overlay';p.appendChild(o)}const pl=plan();o.innerHTML=pl&&pl.signal!=='انتظار'?[[pl.signal==='شراء'?'شراء':'بيع',''],['دخول',fmtP(pl.entry)],['إيقاف',fmtP(pl.stop)],['هدف1',fmtP(pl.tp1)],['هدف2',fmtP(pl.tp2)]].map(x=>'<span class="goldan-plan-chip">'+x[0]+(x[1]?' '+x[1]:'')+'</span>').join(''):'<span class="goldan-plan-chip">لا توجد صفقة مؤكدة الآن · انتظار</span>'}
  function fullscreen(){const p=panel();if(!p)return;p.classList.toggle('chart-fullscreen');const b=p.querySelector('.chart-full-btn');if(b)b.textContent=p.classList.contains('chart-fullscreen')?'✕ شاشة التحليل':'⛶ شاشة التحليل';setTimeout(()=>{draw();refreshOverlay()},30)}
  function aiModal(){
    if(document.querySelector('.goldan-ai-modal'))return;
    const m=document.createElement('div');m.className='goldan-ai-modal';m.innerHTML='<div class="goldan-ai-box"><div class="goldan-ai-head"><div><h3>GOLDAN AI · تحليل الرسم بالصورة</h3><small>تحليل مجاني من الصورة + مطابقة مع بيانات السوق الحية</small></div><button class="goldan-ai-close">✕</button></div><div class="goldan-ai-drop">ارفع صورة الشارت (PNG/JPG)<input type="file" id="goldanImage" accept="image/png,image/jpeg"></div><img id="goldanPreview" class="goldan-ai-preview"><div class="goldan-ai-actions"><button class="goldan-ai-btn" id="goldanAnalyzeImage">تحليل الصورة الآن</button><button class="goldan-ai-btn" id="goldanAnalyzeLive">تحليل السوق الحالي</button></div><div id="goldanAIResult" class="goldan-ai-result">جاهز للتحليل.</div><div class="goldan-ai-warning">مهم: لا يوجد نظام تداول يضمن نتائج صحيحة 100%. الإشارة هنا مبنية على بيانات Binance العامة وقواعد قابلة للفحص، وتحليل الصورة بصري محلي. لا يتم إرسال صورتك إلى خادم خارجي.</div></div>';
    document.body.appendChild(m);m.querySelector('.goldan-ai-close').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')};
    const file=m.querySelector('#goldanImage'),prev=m.querySelector('#goldanPreview');file.onchange=()=>{const f=file.files?.[0];if(!f)return;prev.src=URL.createObjectURL(f);prev.style.display='block'};
    m.querySelector('#goldanAnalyzeLive').onclick=()=>runAIResult(m,false);m.querySelector('#goldanAnalyzeImage').onclick=()=>runAIResult(m,true);m.classList.add('open');
  }
  async function runAIResult(m,withImage){
    const r=m.querySelector('#goldanAIResult');const d=data();const a=typeof analyze==='function'?analyze(d):null;if(!a){r.innerHTML='<b>تعذر التحليل</b>';return}
    const last=d.at(-1),prev=d.at(-2),o=+last[1],h=+last[2],l=+last[3],cl=+last[4],body=Math.abs(cl-o),range=h-l||1;
    let patterns=[];if(body/range<.18)patterns.push('شمعة تردد/دوجي محتملة');if(cl>o&&cl>+prev[4])patterns.push('زخم صاعد');if(cl<o&&cl<+prev[4])patterns.push('زخم هابط');if(h<+prev[2]&&l>+prev[3])patterns.push('شمعة داخلية');
    const pl=plan();r.innerHTML='<b>النتيجة الحالية</b><br>الاتجاه: <b>'+a.signal+'</b> · قوة الإشارة: <b>'+a.confidence+'%</b><br>النموذج/السلوك المرصود: <b>'+((patterns.join(' + '))||'لا يوجد نموذج قوي مؤكد')+'</b><br>منطقة الدخول: <b>'+ (pl&&pl.signal!=='انتظار'?fmtP(pl.entry):'انتظار تأكيد')+'</b><br>إيقاف الخسارة: <b>'+ (pl&&pl.stop?fmtP(pl.stop):'—')+'</b> · الهدف 1: <b>'+ (pl&&pl.tp1?fmtP(pl.tp1):'—')+'</b> · الهدف 2: <b>'+ (pl&&pl.tp2?fmtP(pl.tp2):'—')+'</b><br><span style="color:#75849a">'+a.reasons.slice(0,6).join(' · ')+'</span>' + (withImage?'<br><span style="color:#7fa7d6">تمت قراءة الصورة محليًا كمرجع بصري، ثم تمت مطابقة آخر شمعة مع السوق الحي.</span>':'');
  }
  function setup(){
    const canvas=c(),p=panel();if(!canvas||!p||canvas.dataset.interactive)return;canvas.dataset.interactive='1';
    const tools=document.createElement('div');tools.className='chart-tools';tools.innerHTML='<button class="chart-tool chart-full-btn" type="button">⛶ شاشة التحليل</button><button class="chart-tool" type="button" data-zoom="in">＋ تكبير</button><button class="chart-tool" type="button" data-zoom="out">－ تصغير</button><button class="chart-tool" type="button" id="goldanAiButton">✦ تحليل AI بالصورة</button><span class="chart-hint">اسحب يمين/يسار · قرّب/بعّد</span>';canvas.after(tools);
    tools.querySelector('.chart-full-btn').onclick=fullscreen;tools.querySelector('[data-zoom="in"]').onclick=()=>{view.count=Math.max(25,Math.round(view.count*.8));clamp(state.klines.length);draw();refreshOverlay()};tools.querySelector('[data-zoom="out"]').onclick=()=>{view.count=Math.min(180,Math.round(view.count*1.25));clamp(state.klines.length);draw();refreshOverlay()};tools.querySelector('#goldanAiButton').onclick=aiModal;
    canvas.addEventListener('wheel',e=>{e.preventDefault();view.count=Math.max(25,Math.min(180,Math.round(view.count*(e.deltaY>0?1.12:.89))));clamp(state.klines.length);draw();refreshOverlay()},{passive:false});
    canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);view.drag=true;view.lastX=e.clientX;view.lastY=e.clientY;canvas.classList.add('chart-dragging')});
    canvas.addEventListener('pointermove',e=>{if(!view.drag)return;const dx=e.clientX-view.lastX,dy=e.clientY-view.lastY;view.lastX=e.clientX;view.lastY=e.clientY;const step=Math.max(1,(canvas.clientWidth-70)/view.count);view.start-=Math.round(dx/step);view.yShift+=dy/(canvas.clientHeight||300)*.55;clamp(state.klines.length);view.yShift=Math.max(-.7,Math.min(.7,view.yShift));draw();refreshOverlay()});
    ['pointerup','pointercancel','pointerleave'].forEach(ev=>canvas.addEventListener(ev,()=>{view.drag=false;canvas.classList.remove('chart-dragging')}));
    canvas.addEventListener('dblclick',fullscreen);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&p.classList.contains('chart-fullscreen'))fullscreen()});window.addEventListener('resize',()=>{if(state.klines.length){draw();refreshOverlay()}});
  }
  window.drawChart=draw;setup();setTimeout(()=>{setup();draw();refreshOverlay()},0);
  setInterval(()=>{if(state&&state.klines.length){draw();refreshOverlay()}},3000);
})();
/* GOLDAN AI — TradingView-style toolkit layer (original implementation) */
(function(){
  const TV={inds:new Set(),drawMode:'pan',drawings:[],start:null,count:100,type:'candle'};
  function panel(){const c=document.getElementById('chart');return c&&c.closest('.chart-panel')}
  function canvas(){return document.getElementById('chart')}
  function series(){return (state.liveKline?[...state.klines,state.liveKline]:state.klines).slice()}
  function closes(){return series().map(x=>+x[4])}
  function sma(a,p){const o=Array(a.length).fill(null);let s=0;for(let i=0;i<a.length;i++){s+=a[i];if(i>=p)s-=a[i-p];if(i>=p-1)o[i]=s/p}return o}
  function ema(a,p){const o=Array(a.length).fill(null);if(a.length<p)return o;let e=a.slice(0,p).reduce((x,y)=>x+y,0)/p,k=2/(p+1);o[p-1]=e;for(let i=p;i<a.length;i++){e=a[i]*k+e*(1-k);o[i]=e}return o}
  function bb(a,p,m){const u=Array(a.length).fill(null),l=Array(a.length).fill(null);for(let i=p-1;i<a.length;i++){const z=a.slice(i-p+1,i+1),q=z.reduce((x,y)=>x+y,0)/p,s=Math.sqrt(z.reduce((x,y)=>x+(y-q)*(y-q),0)/p);u[i]=q+m*s;l[i]=q-m*s}return [u,l]}
  function vwap(k){const o=[],pv=0;let p=0,v=0;for(let i=0;i<k.length;i++){const t=(+k[i][2]+ +k[i][3]+ +k[i][4])/3;v+=+k[i][5];p+=t*(+k[i][5]);o[i]=v?p/v:null}return o}
  function css(){if(document.getElementById('tvx-css'))return;const s=document.createElement('style');s.id='tvx-css';s.textContent='.tvx-tool{border:1px solid #263e64;background:#07111f;color:#9dc9ff;border-radius:7px;padding:5px 8px;font-family:inherit;font-size:8px;cursor:pointer;white-space:nowrap}.tvx-menu{position:absolute;z-index:10020;top:42px;right:8px;width:min(330px,calc(100% - 16px));background:#07101c;border:1px solid #28466f;border-radius:14px;padding:10px;box-shadow:0 18px 55px #000c;display:none}.tvx-menu.open{display:block}.tvx-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.tvx-opt,.tvx-draw{border:1px solid #1e3555;background:#0b1726;color:#a9c4e5;border-radius:8px;padding:7px;font-size:8px}.tvx-opt.active,.tvx-draw.active{border-color:#4b8fe8;background:#102a4b;color:#fff}.tvx-drawbar{position:absolute;z-index:10010;left:8px;bottom:44px;display:none;gap:5px;flex-wrap:wrap;background:#07101c;border:1px solid #28466f;border-radius:10px;padding:6px}.tvx-drawbar.open{display:flex}';document.head.appendChild(s)}
  function menu(){const p=panel();if(!p)return null;let m=p.querySelector('.tvx-menu');if(m)m.remove();m=document.createElement('div');m.className='tvx-menu open';m.innerHTML='<div style="font-size:11px;color:#d9e8fb;margin-bottom:8px">مؤشرات التحليل</div><div class="tvx-grid">'+[['sma20','SMA 20'],['ema20','EMA 20'],['bb','Bollinger Bands'],['vwap','VWAP'],['volume','Volume'],['rsi','RSI 14'],['macd','MACD'],['atr','ATR 14']].map(x=>'<button class="tvx-opt '+(TV.inds.has(x[0])?'active':'')+'" data-i="'+x[0]+'">'+x[1]+'</button>').join('')+'</div>';p.appendChild(m);m.querySelectorAll('[data-i]').forEach(b=>b.onclick=function(){const i=b.dataset.i;if(TV.inds.has(i))TV.inds.delete(i);else TV.inds.add(i);b.classList.toggle('active');legend();overlay();});return m}
  function legend(){const e=document.getElementById('indicatorLegend');if(e)e.textContent='ƒx '+(TV.inds.size?[...TV.inds].join(' · '):'لا توجد مؤشرات إضافية')}
  function overlay(){const c=canvas();if(!c||!TV.inds.size)return;const ctx=c.getContext('2d'),k=series(),a=closes();if(k.length<20)return;const w=c.clientWidth,h=c.clientHeight||300,left=8,right=62,top=16,bottom=h-58,n=k.length,count=Math.min(100,n),first=n-count,part=k.slice(first),hi=Math.max.apply(null,part.map(x=>+x[2])),lo=Math.min.apply(null,part.map(x=>+x[3])),range=hi-lo||1,step=(w-left-right)/count,y=function(v){return top+(hi-v)/range*(bottom-top-34)};function line(arr,dash){ctx.save();ctx.strokeStyle='#2f8cff';ctx.lineWidth=1.7;if(dash)ctx.setLineDash([4,3]);ctx.beginPath();let on=false;for(let i=first;i<n;i++){if(arr[i]==null)continue;const x=left+(i-first+.5)*step;if(!on){ctx.moveTo(x,y(arr[i]));on=true}else ctx.lineTo(x,y(arr[i]))}ctx.stroke();ctx.restore()}if(TV.inds.has('sma20'))line(sma(a,20));if(TV.inds.has('ema20'))line(ema(a,20),true);if(TV.inds.has('bb')){const q=bb(a,20,2);line(q[0],true);line(q[1],true)}if(TV.inds.has('vwap'))line(vwap(k));}
  function drawTools(){const p=panel();if(!p)return;let b=p.querySelector('.tvx-drawbar');if(b){b.classList.toggle('open');return}b=document.createElement('div');b.className='tvx-drawbar open';b.innerHTML=[['pan','↖ مؤشر'],['line','╱ خط'],['h','— أفقي'],['v','│ عمودي'],['ray','➜ شعاع'],['rect','□ مستطيل'],['fib','FIB'],['clear','⌫ مسح']].map(x=>'<button class="tvx-draw" data-d="'+x[0]+'">'+x[1]+'</button>').join('');p.appendChild(b);b.querySelectorAll('[data-d]').forEach(x=>x.onclick=function(){TV.drawMode=x.dataset.d;if(TV.drawMode==='clear'){TV.drawings=[];TV.drawMode='pan';draw();overlay();return}b.querySelectorAll('.tvx-draw').forEach(z=>z.classList.toggle('active',z===x));canvas().style.cursor=TV.drawMode==='pan'?'grab':'crosshair'});}
  function drawUser(){const c=canvas();if(!c||!TV.drawings.length)return;const ctx=c.getContext('2d'),k=series(),n=k.length,count=Math.min(100,n),first=n-count,w=c.clientWidth,h=c.clientHeight||300,left=8,right=62,top=16,bottom=h-58,step=(w-left-right)/count,part=k.slice(first),hi=Math.max.apply(null,part.map(x=>+x[2])),lo=Math.min.apply(null,part.map(x=>+x[3])),range=hi-lo||1,y=v=>top+(hi-v)/range*(bottom-top-34);ctx.save();ctx.strokeStyle='#f4c95d';ctx.lineWidth=1.5;TV.drawings.forEach(d=>{const x1=left+(d.i1-first+.5)*step,x2=left+(d.i2-first+.5)*step,y1=y(d.p1),y2=y(d.p2);if(d.type==='h'){ctx.beginPath();ctx.moveTo(left,y1);ctx.lineTo(w-right,y1);ctx.stroke()}else if(d.type==='v'){ctx.beginPath();ctx.moveTo(x1,top);ctx.lineTo(x1,bottom);ctx.stroke()}else if(d.type==='rect'){ctx.globalAlpha=.16;ctx.fillRect(Math.min(x1,x2),Math.min(y1,y2),Math.abs(x2-x1),Math.abs(y2-y1));ctx.globalAlpha=1;ctx.strokeRect(Math.min(x1,x2),Math.min(y1,y2),Math.abs(x2-x1),Math.abs(y2-y1))}else{ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}});ctx.restore()}
  function bind(){css();document.getElementById('indicatorBtn')?.addEventListener('click',menu);document.getElementById('drawingBtn')?.addEventListener('click',drawTools);document.getElementById('chartTypeBtn')?.addEventListener('click',function(){alert('أنواع الرسم المتاحة الآن: شموع. سيتم إضافة خط/منطقة/Heikin Ashi في طبقة الرسم التالية دون تغيير بيانات Binance.')});document.getElementById('compareBtn')?.addEventListener('click',function(){alert('المقارنة متعددة الأصول تحتاج جلب سلسلة ثانية من Binance. زر المقارنة محفوظ، وسأضيفها في خطوة مستقلة حتى لا تتأثر بيانات الشارت الحالي.')});document.getElementById('chartAlertBtn')?.addEventListener('click',function(){document.getElementById('alertBtn')?.click()});const c=canvas();if(!c)return;let down=null;c.addEventListener('pointerdown',function(e){if(TV.drawMode==='pan')return;const r=c.getBoundingClientRect(),k=series(),n=k.length,count=Math.min(100,n),first=n-count,step=(c.clientWidth-70)/count,idx=Math.max(0,Math.min(n-1,first+Math.round((e.clientX-r.left-8)/step-.5))),part=k.slice(first),hi=Math.max.apply(null,part.map(x=>+x[2])),lo=Math.min.apply(null,part.map(x=>+x[3])),price=hi-(e.clientY-r.top-16)/(c.clientHeight-74)*(hi-lo);down={i:idx,p:price}});c.addEventListener('pointerup',function(e){if(!down||TV.drawMode==='pan')return;const r=c.getBoundingClientRect(),k=series(),n=k.length,count=Math.min(100,n),first=n-count,step=(c.clientWidth-70)/count,idx=Math.max(0,Math.min(n-1,first+Math.round((e.clientX-r.left-8)/step-.5))),part=k.slice(first),hi=Math.max.apply(null,part.map(x=>+x[2])),lo=Math.min.apply(null,part.map(x=>+x[3])),price=hi-(e.clientY-r.top-16)/(c.clientHeight-74)*(hi-lo),m=TV.drawMode;if(m==='h')TV.drawings.push({type:'h',i1:idx,i2:idx,p1:price,p2:price});else if(m==='v')TV.drawings.push({type:'v',i1:idx,i2:idx,p1:price,p2:price});else if(['line','ray','rect'].includes(m))TV.drawings.push({type:m,i1:down.i,i2:idx,p1:down.p,p2:price});else if(m==='fib'){const d=price-down.p;[0,.236,.382,.5,.618,.786,1].forEach(q=>TV.drawings.push({type:'h',i1:down.i,i2:idx,p1:down.p+d*q,p2:down.p+d*q}))}down=null;draw();overlay();drawUser()});const old=window.drawChart;window.drawChart=function(){old&&old();overlay();drawUser()};setTimeout(function(){legend();window.drawChart()},200)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();