/* GOLDAN AI — clean live chart + single blue trend line + trade plan + free chart-image analyzer */
(function(){
  const css=`
  .chart-panel{position:relative;overflow:hidden}
  .chart-panel.chart-fullscreen{position:fixed;inset:0;z-index:9999;margin:0;border-radius:0;padding:12px;background:#05070d;overflow:auto}
  .chart-fullscreen canvas{height:calc(100vh - 150px)!important;min-height:360px}
  #chart{touch-action:none;cursor:grab}
  #chart.chart-dragging{cursor:grabbing}
  .chart-tools{display:flex;gap:6px;align-items:center;margin-top:8px;flex-wrap:wrap}
  .chart-tool{border:1px solid #243f75;background:#09111f;color:#6fb2ff;border-radius:9px;padding:7px 10px;font-family:inherit;font-size:9px;cursor:pointer}
  .chart-tool:hover{background:#0d1a2e}
  .chart-hint{color:#646b78;font-size:8px;margin-right:auto}
  .goldan-plan-overlay{position:absolute;left:12px;top:14px;z-index:3;display:flex;gap:5px;flex-wrap:wrap;pointer-events:none}
  .goldan-plan-chip{background:rgba(5,9,16,.9);border:1px solid #203b67;border-radius:8px;padding:4px 7px;color:#a8c9f5;font-size:8px}
  .goldan-ai-modal{position:fixed;inset:0;z-index:10050;background:rgba(2,5,10,.82);display:none;align-items:center;justify-content:center;padding:14px}
  .goldan-ai-modal.open{display:flex}
  .goldan-ai-box{width:min(680px,100%);max-height:92vh;overflow:auto;background:#080d16;border:1px solid #23416d;border-radius:20px;padding:18px;box-shadow:0 24px 80px #000b;color:#eaf2ff}
  .goldan-ai-head{display:flex;align-items:center;justify-content:space-between;gap:10px}
  .goldan-ai-head h3{margin:0;font-size:18px}.goldan-ai-head small{color:#74839a}
  .goldan-ai-close{border:1px solid #263b59;background:#0c1421;color:#b9c8dc;border-radius:9px;padding:6px 10px}
  .goldan-ai-drop{margin-top:14px;border:1px dashed #31527f;border-radius:14px;padding:18px;text-align:center;color:#93a7c2}
  .goldan-ai-drop input{display:block;width:100%;margin-top:10px}
  .goldan-ai-preview{display:none;width:100%;max-height:280px;object-fit:contain;border-radius:12px;margin-top:12px;background:#03060b}
  .goldan-ai-actions{display:flex;gap:7px;margin-top:10px;flex-wrap:wrap}
  .goldan-ai-btn{border:1px solid #315a92;background:#0c1b31;color:#9ac7ff;border-radius:9px;padding:8px 12px;font-family:inherit;font-size:9px}
  .goldan-ai-result{margin-top:13px;border:1px solid #1d304b;border-radius:13px;padding:13px;background:#0a111c;line-height:1.9;font-size:10px}
  .goldan-ai-result b{color:#8dc1ff}.goldan-ai-warning{color:#7e8da1;font-size:8px;margin-top:10px;line-height:1.8}
  `;
  const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
  const c=()=>document.getElementById('chart'), panel=()=>c()&&c().closest('.chart-panel');
  const view={start:null,count:90,yShift:0,drag:false,lastX:0,lastY:0};
  function data(){return state.liveKline?[...state.klines.slice(0,-1),state.liveKline]:state.klines.slice()}
  function sma(v,p){const o=Array(v.length).fill(null);let s=0;for(let i=0;i<v.length;i++){s+=v[i];if(i>=p)s-=v[i-p];if(i>=p-1)o[i]=s/p}return o}
  function clamp(n){view.count=Math.max(25,Math.min(180,view.count));view.start=Math.max(0,Math.min(Math.max(0,n-view.count),view.start==null?Math.max(0,n-view.count):view.start))}
  function fmtP(v){return v>=10000?fmt(v,2):v>=100?fmt(v,2):v>=1?fmt(v,4):fmt(v,6)}
  function drawLine(ctx,arr,first,step,y){ctx.strokeStyle='#2f8cff';ctx.lineWidth=2.4;ctx.beginPath();let started=false;for(let i=first;i<Math.min(arr.length,first+view.count);i++){const v=arr[i];if(v==null)continue;const x=8+(i-first+.5)*step,yy=y(v);if(!started){ctx.moveTo(x,yy);started=true}else ctx.lineTo(x,yy)}if(started)ctx.stroke()}
  function plan(){const p=state.lastPrice||(+state.klines.at(-1)?.[4]||0),a=typeof analyze==='function'?analyze(data()):null;if(!p||!a)return null;const dir=a.signal==='شراء'?1:a.signal==='بيع'?-1:0;const atr=a.atr||p*.003;return{signal:a.signal,entry:p,stop:dir?p-dir*atr*1.4:null,tp1:dir?p+dir*atr*2:null,tp2:dir?p+dir*atr*3.2:null,score:a.score}}
  function draw(){const canvas=c();if(!canvas||!state||!state.klines.length)return;const ctx=canvas.getContext('2d'),dpr=devicePixelRatio||1,w=Math.max(1,canvas.clientWidth),h=Math.max(320,canvas.clientHeight||320);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const all=data(),n=all.length;clamp(n);const first=view.start,last=Math.min(n,first+view.count),k=all.slice(first,last);if(k.length<2)return;const closes=all.map(x=>+x[4]),trend=sma(closes,21);let hi=Math.max(...k.map(x=>+x[2])),lo=Math.min(...k.map(x=>+x[3]));for(let i=first;i<last;i++)if(trend[i]!=null){hi=Math.max(hi,trend[i]);lo=Math.min(lo,trend[i])}const extra=(hi-lo||1)*.08;hi+=extra;lo-=extra;const left=8,right=62,top=16,bottom=h-58,range=hi-lo,cw=(w-left-right)/k.length,y=v=>top+(hi-v)/range*(bottom-top-34);ctx.font='10px Cairo';for(let j=0;j<6;j++){const yy=top+j*(bottom-top)/5;ctx.strokeStyle='#171c23';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(w-right,yy);ctx.stroke();ctx.fillStyle='#707887';ctx.fillText('$'+fmtP(hi-j*range/5),w-right+5,yy+3)}const vh=Math.max(...k.map(x=>+x[5]))||1;k.forEach((x,i)=>{const o=+x[1],hh=+x[2],ll=+x[3],cl=+x[4],cx=left+i*cw+cw/2,up=cl>=o,col=up?'#43dfa0':'#ff637d';ctx.strokeStyle=col;ctx.fillStyle=col;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(cx,y(hh));ctx.lineTo(cx,y(ll));ctx.stroke();ctx.fillRect(cx-Math.max(2,cw*.56)/2,Math.min(y(o),y(cl)),Math.max(2,cw*.56),Math.max(2,Math.abs(y(o)-y(cl))));const bh=(+x[5]/vh)*28;ctx.globalAlpha=.18;ctx.fillRect(cx-cw*.28,h-39-bh,Math.max(2,cw*.56),bh);ctx.globalAlpha=1});drawLine(ctx,trend,first,cw,y);const current=state.lastPrice||+all[n-1][4],py=y(current);ctx.setLineDash([5,4]);ctx.strokeStyle='#8a95a5';ctx.globalAlpha=.45;ctx.beginPath();ctx.moveTo(left,py);ctx.lineTo(w-right,py);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;const pl=plan();if(pl&&pl.signal!=='انتظار'){[['ENTRY',pl.entry],['SL',pl.stop],['TP1',pl.tp1],['TP2',pl.tp2]].forEach((q,idx)=>{if(q[1]==null)return;const yy=y(q[1]);ctx.setLineDash([3,4]);ctx.strokeStyle=idx===1?'#ff637d':idx>1?'#43dfa0':'#6faeff';ctx.globalAlpha=.6;ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(w-right,yy);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;ctx.fillStyle=idx===1?'#ff8295':idx>1?'#66e4aa':'#82b8ff';ctx.fillText(q[0]+' '+fmtP(q[1]),left+5,yy-3)})}ctx.font='8px Cairo';ctx.fillStyle='#6f7886';ctx.fillText('● الأزرق = خط GOLDAN Trend · LIVE Binance',left,h-24);ctx.fillText(`${k.length} شمعة · اسحب للتحريك · قرّب/بعّد`,left,h-9)}
  function refreshOverlay(){const p=panel();if(!p)return;let o=p.querySelector('.goldan-plan-overlay');if(!o){o=document.createElement('div');o.className='goldan-plan-overlay';p.appendChild(o)}const pl=plan();o.innerHTML=pl&&pl.signal!=='انتظار'?[['شراء/بيع',pl.signal],['دخول',fmtP(pl.entry)],['إيقاف',fmtP(pl.stop)],['هدف1',fmtP(pl.tp1)],['هدف2',fmtP(pl.tp2)]].map(x=>'<span class="goldan-plan-chip">'+x[0]+' '+x[1]+'</span>').join(''):'<span class="goldan-plan-chip">لا توجد صفقة مؤكدة الآن · انتظار</span>'}
  function fullscreen(){const p=panel();if(!p)return;p.classList.toggle('chart-fullscreen');const b=p.querySelector('.chart-full-btn');if(b)b.textContent=p.classList.contains('chart-fullscreen')?'✕ شاشة التحليل':'⛶ شاشة التحليل';setTimeout(()=>{draw();refreshOverlay()},30)}
  function aiModal(){if(document.querySelector('.goldan-ai-modal')){document.querySelector('.goldan-ai-modal').classList.add('open');return}const m=document.createElement('div');m.className='goldan-ai-modal';m.innerHTML='<div class="goldan-ai-box"><div class="goldan-ai-head"><div><h3>GOLDAN AI · تحليل الرسم بالصورة</h3><small>تحليل مجاني من الصورة + مطابقة مع بيانات السوق الحية</small></div><button class="goldan-ai-close">✕</button></div><div class="goldan-ai-drop">ارفع صورة الشارت (PNG/JPG)<input type="file" id="goldanImage" accept="image/png,image/jpeg"></div><img id="goldanPreview" class="goldan-ai-preview"><div class="goldan-ai-actions"><button class="goldan-ai-btn" id="goldanAnalyzeImage">تحليل الصورة الآن</button><button class="goldan-ai-btn" id="goldanAnalyzeLive">تحليل السوق الحالي</button></div><div id="goldanAIResult" class="goldan-ai-result">جاهز للتحليل.</div><div class="goldan-ai-warning">مهم: لا يوجد نظام تداول يضمن نتائج صحيحة 100%. الإشارة مبنية على بيانات Binance العامة وقواعد قابلة للفحص.</div></div>';document.body.appendChild(m);m.querySelector('.goldan-ai-close').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')};const file=m.querySelector('#goldanImage'),prev=m.querySelector('#goldanPreview');file.onchange=()=>{const f=file.files?.[0];if(f){prev.src=URL.createObjectURL(f);prev.style.display='block'}};m.querySelector('#goldanAnalyzeLive').onclick=()=>runAIResult(m,false);m.querySelector('#goldanAnalyzeImage').onclick=()=>runAIResult(m,true);m.classList.add('open')}
  async function runAIResult(m,withImage){const r=m.querySelector('#goldanAIResult'),d=data(),a=typeof analyze==='function'?analyze(d):null;if(!a){r.innerHTML='<b>تعذر التحليل</b>';return}const last=d.at(-1),prev=d.at(-2),o=+last[1],h=+last[2],l=+last[3],cl=+last[4],body=Math.abs(cl-o),range=h-l||1;let patterns=[];if(body/range<.18)patterns.push('شمعة تردد/دوجي محتملة');if(cl>o&&cl>+prev[4])patterns.push('زخم صاعد');if(cl<o&&cl<+prev[4])patterns.push('زخم هابط');if(h<+prev[2]&&l>+prev[3])patterns.push('شمعة داخلية');const pl=plan();r.innerHTML='<b>النتيجة الحالية</b><br>الاتجاه: <b>'+a.signal+'</b> · قوة الإشارة: <b>'+a.confidence+'%</b><br>السلوك: <b>'+((patterns.join(' + '))||'لا يوجد نموذج قوي مؤكد')+'</b><br>الدخول: <b>'+ (pl&&pl.signal!=='انتظار'?fmtP(pl.entry):'انتظار تأكيد')+'</b><br>إيقاف: <b>'+ (pl&&pl.stop?fmtP(pl.stop):'—')+'</b> · الهدف 1: <b>'+ (pl&&pl.tp1?fmtP(pl.tp1):'—')+'</b> · الهدف 2: <b>'+ (pl&&pl.tp2?fmtP(pl.tp2):'—')+'</b><br><span style="color:#75849a">'+a.reasons.slice(0,6).join(' · ')+'</span>' + (withImage?'<br><span style="color:#7fa7d6">تمت قراءة الصورة محليًا كمرجع بصري.</span>':'')}
  }
  function setup(){const canvas=c(),p=panel();if(!canvas||!p||canvas.dataset.interactive)return;canvas.dataset.interactive='1';const tools=document.createElement('div');tools.className='chart-tools';tools.innerHTML='<button class="chart-tool chart-full-btn" type="button">⛶ شاشة التحليل</button><button class="chart-tool" type="button" data-zoom="in">＋ تكبير</button><button class="chart-tool" type="button" data-zoom="out">－ تصغير</button><button class="chart-tool" type="button" id="goldanAiButton">✦ تحليل AI بالصورة</button><span class="chart-hint">اسحب يمين/يسار · قرّب/بعّد</span>';canvas.after(tools);tools.querySelector('.chart-full-btn').onclick=fullscreen;tools.querySelector('[data-zoom="in"]').onclick=()=>{view.count=Math.max(25,Math.round(view.count*.8));clamp(state.klines.length);draw();refreshOverlay()};tools.querySelector('[data-zoom="out"]').onclick=()=>{view.count=Math.min(180,Math.round(view.count*1.25));clamp(state.klines.length);draw();refreshOverlay()};tools.querySelector('#goldanAiButton').onclick=aiModal;canvas.addEventListener('wheel',e=>{e.preventDefault();view.count=Math.max(25,Math.min(180,Math.round(view.count*(e.deltaY>0?1.12:.89))));clamp(state.klines.length);draw();refreshOverlay()},{passive:false});canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);view.drag=true;view.lastX=e.clientX;view.lastY=e.clientY;canvas.classList.add('chart-dragging')});canvas.addEventListener('pointermove',e=>{if(!view.drag)return;const dx=e.clientX-view.lastX,dy=e.clientY-view.lastY;view.lastX=e.clientX;view.lastY=e.clientY;const step=Math.max(1,(canvas.clientWidth-70)/view.count);view.start-=Math.round(dx/step);view.yShift+=dy/(canvas.clientHeight||300)*.55;clamp(state.klines.length);view.yShift=Math.max(-.7,Math.min(.7,view.yShift));draw();refreshOverlay()});['pointerup','pointercancel','pointerleave'].forEach(ev=>canvas.addEventListener(ev,()=>{view.drag=false;canvas.classList.remove('chart-dragging')}));canvas.addEventListener('dblclick',fullscreen);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&p.classList.contains('chart-fullscreen'))fullscreen()});window.addEventListener('resize',()=>{if(state.klines.length){draw();refreshOverlay()}})}
  window.drawChart=draw;setup();setTimeout(()=>{setup();draw();refreshOverlay()},0);setInterval(()=>{if(state&&state.klines.length){draw();refreshOverlay()}},3000);
})();

/* GOLDAN AI — TradingView-style full chart workspace, original code */
(function(){
  const T={type:'candle',inds:new Set(),mode:'pan',drawings:[],compare:'BTCUSDT',second:null,alerts:[],visible:100,first:null};
  const C=()=>document.getElementById('chart'), P=()=>C()?.closest('.chart-panel');
  const K=()=>state.liveKline?[...state.klines.slice(0,-1),state.liveKline]:state.klines.slice();
  const A=()=>K().map(x=>+x[4]);
  const q=(a,p)=>{const o=Array(a.length).fill(null);if(!a.length)return o;let s=0;for(let i=0;i<a.length;i++){s+=a[i];if(i>=p)s-=a[i-p];if(i>=p-1)o[i]=s/p}return o};
  const e=(a,p)=>{const o=Array(a.length).fill(null);if(a.length<p)return o;let z=a.slice(0,p).reduce((x,y)=>x+y,0)/p,k=2/(p+1);o[p-1]=z;for(let i=p;i<a.length;i++){z=a[i]*k+z*(1-k);o[i]=z}return o};
  const sd=(a,p,i)=>{const z=a.slice(i-p+1,i+1),m=z.reduce((x,y)=>x+y,0)/p;return Math.sqrt(z.reduce((x,y)=>x+(y-m)**2,0)/p)};
  const bb=(a,p,m)=>{const u=Array(a.length).fill(null),l=Array(a.length).fill(null),mid=q(a,p);for(let i=p-1;i<a.length;i++){const s=sd(a,p,i);u[i]=mid[i]+m*s;l[i]=mid[i]-m*s}return [u,l]};
  const rsi=a=>{const o=Array(a.length).fill(null);if(a.length<15)return o;let g=0,l=0;for(let i=1;i<=14;i++){const d=a[i]-a[i-1];g+=Math.max(0,d);l+=Math.max(0,-d)}g/=14;l/=14;o[14]=l?100-100/(1+g/l):100;for(let i=15;i<a.length;i++){const d=a[i]-a[i-1];g=(g*13+Math.max(0,d))/14;l=(l*13+Math.max(0,-d))/14;o[i]=l?100-100/(1+g/l):100}return o};
  const macd=a=>{const f=e(a,12),s=e(a,26),m=a.map((_,i)=>f[i]!=null&&s[i]!=null?f[i]-s[i]:null),sig=e(m.map(x=>x??0),9);return [m,sig]};
  const atr=k=>{const tr=Array(k.length).fill(null);for(let i=1;i<k.length;i++){const h=+k[i][2],l=+k[i][3],pc=+k[i-1][4];tr[i]=Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc))}return q(tr.map(x=>x??0),14)};
  const vwap=k=>{let pv=0,v=0;return k.map(x=>{const p=(+x[2]+ +x[3]+ +x[4])/3;v+=+x[5];pv+=p*(+x[5]);return v?pv/v:null})};
  function style(){if(document.getElementById('goldan-tv-style'))return;const s=document.createElement('style');s.id='goldan-tv-style';s.textContent='.gtv-pop{position:absolute;z-index:10030;top:42px;left:8px;right:8px;max-height:70vh;overflow:auto;background:#07101b;border:1px solid #29476f;border-radius:14px;padding:10px;box-shadow:0 20px 70px #000c}.gtv-head{display:flex;justify-content:space-between;gap:6px;align-items:center;margin-bottom:8px;color:#dceaff}.gtv-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.gtv-btn{border:1px solid #23405f;background:#0a1726;color:#a8c8e9;border-radius:8px;padding:7px;font:inherit;font-size:9px}.gtv-btn.on{border-color:#4e96ff;background:#102b4b;color:#fff}.gtv-section{margin:10px 0 5px;color:#6eaaff;font-size:9px}.gtv-drawbar{position:absolute;z-index:10025;left:8px;right:8px;bottom:44px;display:flex;gap:5px;flex-wrap:wrap;background:#07101b;border:1px solid #29476f;border-radius:10px;padding:7px}.gtv-alert{position:absolute;z-index:10040;right:10px;bottom:10px;background:#0a1523;border:1px solid #3b73b8;border-radius:9px;padding:8px;color:#dceaff;font-size:9px}.gtv-hide{display:none!important}';document.head.appendChild(s)}
  function menu(title,body){const p=P();if(!p)return; p.querySelectorAll('.gtv-pop').forEach(x=>x.remove());const m=document.createElement('div');m.className='gtv-pop';m.innerHTML='<div class="gtv-head"><b>'+title+'</b><button class="gtv-btn" data-close>✕</button></div>'+body;p.appendChild(m);m.querySelector('[data-close]').onclick=()=>m.remove();return m}
  function indicators(){style();const names=[['sma20','SMA 20'],['sma50','SMA 50'],['ema20','EMA 20'],['ema50','EMA 50'],['bb','Bollinger'],['vwap','VWAP'],['volume','Volume'],['rsi','RSI 14'],['macd','MACD'],['atr','ATR 14']];const m=menu('المؤشرات', '<div class="gtv-grid">'+names.map(x=>'<button class="gtv-btn '+(T.inds.has(x[0])?'on':'')+'" data-i="'+x[0]+'">'+x[1]+'</button>').join('')+'</div>');m?.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const i=b.dataset.i;T.inds.has(i)?T.inds.delete(i):T.inds.add(i);b.classList.toggle('on',T.inds.has(i));draw();legend()})}
  function chartTypes(){style();const types=[['candle','شموع'],['hollow','شموع مجوفة'],['line','خط'],['area','منطقة'],['bar','أعمدة OHLC'],['heikin','Heikin Ashi'],['baseline','Baseline'],['columns','أعمدة'],['volume','شموع + حجم']];const m=menu('نوع الرسم', '<div class="gtv-grid">'+types.map(x=>'<button class="gtv-btn '+(T.type===x[0]?'on':'')+'" data-t="'+x[0]+'">'+x[1]+'</button>').join('')+'</div><div class="gtv-section">ملاحظة</div><small style="color:#72839a">الرسوم تعتمد على بيانات Binance المتاحة داخل التطبيق.</small>');m?.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{T.type=b.dataset.t;m.remove();draw();legend()})}
  function drawings(){style();const ds=[['pan','مؤشر/تحريك'],['line','خط اتجاه'],['ray','شعاع'],['h','خط أفقي'],['v','خط عمودي'],['channel','قناة'],['rect','مستطيل'],['circle','دائرة'],['fib','Fibonacci'],['measure','قياس'],['text','نص'],['clear','مسح الكل']];const m=menu('أدوات الرسم','<div class="gtv-grid">'+ds.map(x=>'<button class="gtv-btn" data-d="'+x[0]+'">'+x[1]+'</button>').join('')+'</div><div class="gtv-section">تحكم</div><div class="gtv-grid"><button class="gtv-btn" data-d="undo">↶ تراجع</button><button class="gtv-btn" data-d="hide">إخفاء الرسومات</button></div>');m?.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{const d=b.dataset.d;if(d==='clear'){T.drawings=[];T.mode='pan';draw();return}if(d==='undo'){T.drawings.pop();draw();return}if(d==='hide'){T.hidden=!T.hidden;draw();return}T.mode=d;m.remove();C().style.cursor=d==='pan'?'grab':'crosshair'})}
  function compare(){style();const syms=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','ADAUSDT','DOGEUSDT','AVAXUSDT'];const m=menu('مقارنة الأصول','<div class="gtv-grid">'+syms.map(x=>'<button class="gtv-btn '+(T.compare===x?'on':'')+'" data-s="'+x+'">'+x+'</button>').join('')+'</div><div class="gtv-section">المقارنة الحالية</div><small style="color:#72839a">يتم تطبيع السلسلة المختارة إلى نسبة تغير من أول شمعة. سيتم جلبها من Binance العام عند توفر الاتصال.</small>');m?.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{T.compare=b.dataset.s;m.remove();fetchCompare(T.compare);draw()})}
  async function fetchCompare(sym){try{const u='https://api.binance.com/api/v3/klines?symbol='+encodeURIComponent(sym)+'&interval='+(window.currentInterval||'5m')+'&limit=100';const r=await fetch(u);if(!r.ok)throw 0;T.second=await r.json();draw()}catch(_){T.second=null}}
  function alertMenu(){style();const m=menu('تنبيه السعر','<div class="gtv-grid"><button class="gtv-btn" data-a="above">السعر أعلى من</button><button class="gtv-btn" data-a="below">السعر أقل من</button><button class="gtv-btn" data-a="cross">تقاطع السعر</button><button class="gtv-btn" data-a="signal">إشارة GOLDAN</button></div><div style="margin-top:8px"><input id="gtvAlertPrice" inputmode="decimal" placeholder="السعر" style="width:100%;box-sizing:border-box;background:#0a1726;border:1px solid #29476f;border-radius:8px;padding:8px;color:#fff"></div><small style="color:#72839a;display:block;margin-top:8px">التنبيه المحلي يعمل عندما تكون صفحة التطبيق مفتوحة. إشعارات الخلفية الكاملة تحتاج خدمة إشعارات/Push مستقلة.</small>');m?.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{const p=+m.querySelector('#gtvAlertPrice')?.value;if(b.dataset.a==='signal'){T.alerts.push({type:'signal'});notify('تم تفعيل تنبيه إشارة GOLDAN');}else if(p>0){T.alerts.push({type:b.dataset.a,price:p});notify('تم حفظ التنبيه عند '+p)}else notify('أدخل السعر أولاً')})}
  function notify(msg){let p=P();if(!p)return;const n=document.createElement('div');n.className='gtv-alert';n.textContent=msg;p.appendChild(n);setTimeout(()=>n.remove(),3500)}
  function checkAlerts(){const p=state.lastPrice||+K().at(-1)?.[4]||0;T.alerts=T.alerts.filter(a=>{if(a.type==='above'&&p>=a.price){notify('🔔 السعر وصل '+p);return false}if(a.type==='below'&&p<=a.price){notify('🔔 السعر وصل '+p);return false}return true})}
  function legend(){const e=document.getElementById('indicatorLegend');if(e)e.textContent=T.inds.size?'ƒx '+[...T.inds].join(' · '):'ƒx لا توجد مؤشرات إضافية';const l=document.getElementById('chartModeLabel');if(l)l.textContent='الرسم: '+T.type}
  function range(){const c=C(),k=K(),n=k.length;if(!c||!n)return null;const w=c.clientWidth,h=c.clientHeight||320,left=8,right=66,top=14,bottom=h-64,count=Math.min(T.visible,n);if(T.first==null)T.first=Math.max(0,n-count);T.first=Math.max(0,Math.min(n-count,T.first));const part=k.slice(T.first,T.first+count);let hi=Math.max(...part.map(x=>+x[2])),lo=Math.min(...part.map(x=>+x[3]));return{c,k,n,w,h,left,right,top,bottom,count,first:T.first,part,hi,lo,step:(w-left-right)/count}}
  function render(){const R=range();if(!R)return;const {c,k,w,h,left,right,top,bottom,count,first,part,hi:rawHi,lo:rawLo,step}=R;const ctx=c.getContext('2d'),d=devicePixelRatio||1;c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);let hi=rawHi,lo=rawLo;const close=A(), overlays=[];for(const i of T.inds){if(i==='sma20')overlays.push(['SMA20',q(close,20),1]);if(i==='sma50')overlays.push(['SMA50',q(close,50),1]);if(i==='ema20')overlays.push(['EMA20',e(close,20),1]);if(i==='ema50')overlays.push(['EMA50',e(close,50),1]);if(i==='bb'){const z=bb(close,20,2);overlays.push(['BBU',z[0],1],['BBL',z[1],1])}if(i==='vwap')overlays.push(['VWAP',vwap(k),1])}for(const z of overlays.slice(0,8))for(let i=first;i<first+count;i++)if(z[1][i]!=null){hi=Math.max(hi,z[1][i]);lo=Math.min(lo,z[1][i])}const pad=(hi-lo||1)*.08;hi+=pad;lo-=pad;const y=v=>top+(hi-v)/(hi-lo)*(bottom-top),x=i=>left+(i-first+.5)*step;ctx.font='10px Cairo';for(let j=0;j<6;j++){const yy=top+j*(bottom-top)/5;ctx.strokeStyle='#171c23';ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(w-right,yy);ctx.stroke();ctx.fillStyle='#707887';ctx.fillText(fmtP(hi-j*(hi-lo)/5),w-right+5,yy+3)}
    const heikin=[];for(let i=0;i<part.length;i++){const z=part[i],o=+z[1],hh=+z[2],ll=+z[3],cl=+z[4];if(i===0)heikin.push([o,hh,ll,cl]);else{const prev=heikin[i-1];const hc=(o+hh+ll+cl)/4,ho=(prev[0]+prev[3])/2;heikin.push([ho,Math.max(hh,ho,hc),Math.min(ll,ho,hc),hc])}}
    part.forEach((z,i)=>{let o=+z[1],hh=+z[2],ll=+z[3],cl=+z[4];if(T.type==='heikin'){[o,hh,ll,cl]=heikin[i]}const xx=x(first+i),up=cl>=o,col=up?'#43dfa0':'#ff637d';ctx.strokeStyle=col;ctx.fillStyle=col;ctx.lineWidth=1;if(['line','area','baseline'].includes(T.type))return; if(T.type==='bar'){ctx.beginPath();ctx.moveTo(xx,y(hh));ctx.lineTo(xx,y(ll));ctx.moveTo(xx-5,y(o));ctx.lineTo(xx,y(o));ctx.moveTo(xx,y(cl));ctx.lineTo(xx+5,y(cl));ctx.stroke()}else if(T.type==='columns'){ctx.globalAlpha=.75;ctx.fillRect(xx-step*.32,y(cl),step*.64,Math.max(1,bottom-y(cl)));ctx.globalAlpha=1}else{ctx.beginPath();ctx.moveTo(xx,y(hh));ctx.lineTo(xx,y(ll));ctx.stroke();if(T.type==='hollow')ctx.fillStyle='transparent';ctx.fillRect(xx-Math.max(2,step*.56)/2,Math.min(y(o),y(cl)),Math.max(2,step*.56),Math.max(2,Math.abs(y(o)-y(cl))))}});
    if(['line','area','baseline'].includes(T.type)){ctx.beginPath();for(let i=0;i<part.length;i++){const yy=y(+part[i][4]),xx=x(first+i);if(i===0)ctx.moveTo(xx,yy);else ctx.lineTo(xx,yy)}ctx.strokeStyle='#6fb2ff';ctx.lineWidth=2;ctx.stroke();if(T.type==='area'){ctx.lineTo(x(first+part.length-1),bottom);ctx.lineTo(x(first),bottom);ctx.closePath();ctx.globalAlpha=.12;ctx.fillStyle='#3b8cff';ctx.fill();ctx.globalAlpha=1}if(T.type==='baseline'){const base=(hi+lo)/2;ctx.setLineDash([4,3]);ctx.strokeStyle='#667384';ctx.beginPath();ctx.moveTo(left,y(base));ctx.lineTo(w-right,y(base));ctx.stroke();ctx.setLineDash([])}}
    for(const z of overlays){ctx.beginPath();let on=false;ctx.strokeStyle=z[0].startsWith('BB')?'#8a9cff':z[0].startsWith('VWAP')?'#f0c86a':'#2f8cff';ctx.lineWidth=1.5;for(let i=first;i<first+count;i++){const v=z[1][i];if(v==null)continue;const xx=x(i),yy=y(v);if(!on){ctx.moveTo(xx,yy);on=true}else ctx.lineTo(xx,yy)}if(on)ctx.stroke()}
    if(T.inds.has('volume')){const mv=Math.max(...part.map(z=>+z[5]))||1;part.forEach((z,i)=>{ctx.globalAlpha=.2;ctx.fillStyle=+z[4]>=+z[1]?'#43dfa0':'#ff637d';ctx.fillRect(x(first+i)-step*.3,bottom-(+z[5]/mv)*30,step*.6,(+z[5]/mv)*30);ctx.globalAlpha=1})}
    const panels=[];if(T.inds.has('rsi'))panels.push(['RSI',rsi(close),0,100]);if(T.inds.has('macd')){const m=macd(close);panels.push(['MACD',m[0],null,null],['SIGNAL',m[1],null,null])}if(T.inds.has('atr'))panels.push(['ATR',atr(k),null,null]);if(panels.length){const ph=Math.min(110,Math.max(65,(bottom-top)*.26));let py=bottom-ph;for(const pa of panels){ctx.strokeStyle='#202a39';ctx.beginPath();ctx.moveTo(left,py);ctx.lineTo(w-right,py);ctx.stroke();ctx.strokeStyle=pa[0]==='RSI'?'#c18cff':'#5bb7ff';ctx.beginPath();let on=false;const arr=pa[1];let mx=pa[3]??Math.max(...arr.filter(v=>v!=null),1),mn=pa[2]??Math.min(...arr.filter(v=>v!=null),0),rg=mx-mn||1;for(let i=first;i<first+count;i++){if(arr[i]==null)continue;const xx=x(i),yy=py+ph-(arr[i]-mn)/rg*(ph-12);if(!on){ctx.moveTo(xx,yy);on=true}else ctx.lineTo(xx,yy)}if(on)ctx.stroke();ctx.fillStyle='#73839a';ctx.font='8px Cairo';ctx.fillText(pa[0],left+4,py+12);py-=Math.min(70,ph*.6)}}
    if(!T.hidden)drawDrawings(ctx,R,hi,lo);ctx.fillStyle='#697587';ctx.font='8px Cairo';ctx.fillText('GOLDAN AI · '+T.type+' · Binance LIVE',left,h-12);checkAlerts();legend();
  }
  function drawDrawings(ctx,R,hi,lo){const {left,right,top,bottom,step,first}=R;const y=v=>top+(hi-v)/(hi-lo)*(bottom-top);const xx=i=>left+(i-first+.5)*step;ctx.save();ctx.strokeStyle='#f3c95e';ctx.fillStyle='#f3c95e';ctx.lineWidth=1.4;for(const z of T.drawings){const x1=xx(z.i1),x2=xx(z.i2),y1=y(z.p1),y2=y(z.p2);if(z.type==='h'){ctx.beginPath();ctx.moveTo(left,y1);ctx.lineTo(R.w-right,y1);ctx.stroke()}else if(z.type==='v'){ctx.beginPath();ctx.moveTo(x1,top);ctx.lineTo(x1,bottom);ctx.stroke()}else if(z.type==='rect'){ctx.strokeRect(Math.min(x1,x2),Math.min(y1,y2),Math.abs(x2-x1),Math.abs(y2-y1))}else if(z.type==='circle'){ctx.beginPath();ctx.ellipse((x1+x2)/2,(y1+y2)/2,Math.abs(x2-x1)/2,Math.abs(y2-y1)/2,0,0,Math.PI*2);ctx.stroke()}else if(z.type==='channel'){const dy=y2-y1;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.moveTo(x1,y1+dy*.35);ctx.lineTo(x2,y2+dy*.35);ctx.stroke()}else if(z.type==='fib'){const d=z.p2-z.p1;[0,.236,.382,.5,.618,.786,1].forEach(qv=>{const yy=y(z.p1+d*qv);ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(R.w-right,yy);ctx.stroke();ctx.fillText((qv*100).toFixed(1)+'%',left+4,yy-2)})}else if(z.type==='text'){ctx.fillText(z.text||'GOLDAN',x1,y1)}else if(z.type==='measure'){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.fillText((z.p2-z.p1).toFixed(4),x2,y2-4)}else{ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);if(z.type==='ray')ctx.lineTo(x2+(x2-x1)*5,y2+(y2-y1)*5);ctx.stroke()}}ctx.restore()}
  function point(e,R){const r=C().getBoundingClientRect(),idx=Math.max(0,Math.min(R.n-1,R.first+Math.round((e.clientX-r.left-R.left)/R.step-.5))),price=R.hi-(e.clientY-r.top-R.top)/(R.bottom-R.top)*(R.hi-R.lo);return{i:idx,p:price}}
  function bindDraw(){const c=C();if(!c||c.dataset.gtvbound)return;c.dataset.gtvbound='1';let down=null;c.addEventListener('pointerdown',e=>{if(T.mode==='pan')return;const R=range();if(R)down=point(e,R)});c.addEventListener('pointerup',e=>{if(!down||T.mode==='pan')return;const R=range();if(!R)return;const b=point(e,R),m=T.mode;if(m==='h'||m==='v')T.drawings.push({type:m,i1:b.i,i2:b.i,p1:b.p,p2:b.p});else if(m==='text'){const text=prompt('اكتب النص:','GOLDAN');if(text)T.drawings.push({type:m,i1:b.i,i2:b.i,p1:b.p,p2:b.p,text})}else if(m==='measure'||m==='line'||m==='ray'||m==='rect'||m==='circle'||m==='channel'||m==='fib')T.drawings.push({type:m,i1:down.i,i2:b.i,p1:down.p,p2:b.p});down=null;T.mode='pan';c.style.cursor='grab';draw()})}
  function toolbar(){style();document.getElementById('chartTypeBtn')?.addEventListener('click',chartTypes);document.getElementById('indicatorBtn')?.addEventListener('click',indicators);document.getElementById('drawingBtn')?.addEventListener('click',drawings);document.getElementById('compareBtn')?.addEventListener('click',compare);document.getElementById('chartAlertBtn')?.addEventListener('click',alertMenu);bindDraw();document.addEventListener('keydown',e=>{if(e.key==='Escape')P()?.querySelectorAll('.gtv-pop').forEach(x=>x.remove())})}
  async function draw(){render()}
  window.goldanTradingViewRender=draw;window.goldanTVState=T;toolbar();setTimeout(draw,100);setInterval(draw,1200);
})();